export type CategoryKey =
  | "hombre"
  | "mujer"
  | "ninos"
  | "ninas"
  | "calzado"
  | "bolsos"
  | "joyeria"
  | "accesorios"
  | "fragancias"
  | "skincare"
  | "cuidado"
  | "maquillaje";

export type ColorOption = { name: string; hex: string };

export type Product = {
  id: string;
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  price: number;
  image: string;
  images: string[];
  category: CategoryKey;
  categoryLabel: string;
  type: string;
  style: string;
  material: string;
  availability: string;
  colors: ColorOption[];
  sizes: string[];
  rating: number;
  badge?: "Nuevo" | "Oferta" | "Más vendido";
};

const categoryFallbackVisual = (label: string) => {
  const safe = label.replace(/[&<>"']/g, "");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="750"><rect width="100%" height="100%" fill="#f5f5f4"/><text x="50%" y="48%" text-anchor="middle" font-family="Arial" font-size="34" fill="#292524">NOVASTYLE</text><text x="50%" y="55%" text-anchor="middle" font-family="Arial" font-size="22" fill="#78716c">${safe}</text></svg>`;
  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
};

/** Imagen local de respaldo por categoría. Se usa solo si una imagen real falla al cargar. */
export const FALLBACK_IMAGE: Record<CategoryKey, string> = {
  hombre: categoryFallbackVisual("Hombre"),
  mujer: categoryFallbackVisual("Mujer"),
  ninos: categoryFallbackVisual("Niños"),
  ninas: categoryFallbackVisual("Niñas"),
  calzado: categoryFallbackVisual("Calzado"),
  bolsos: categoryFallbackVisual("Bolsos"),
  joyeria: categoryFallbackVisual("Joyería"),
  accesorios: categoryFallbackVisual("Accesorios"),
  fragancias: categoryFallbackVisual("Fragancias"),
  skincare: categoryFallbackVisual("Skincare"),
  cuidado: categoryFallbackVisual("Cuidado personal"),
  maquillaje: categoryFallbackVisual("Maquillaje"),
};

export const CATEGORY_LABEL: Record<CategoryKey, string> = {
  hombre: "Hombre",
  mujer: "Mujer",
  ninos: "Niños",
  ninas: "Niñas",
  calzado: "Calzado",
  bolsos: "Bolsos",
  joyeria: "Joyería",
  accesorios: "Accesorios",
  fragancias: "Fragancias",
  skincare: "Skincare",
  cuidado: "Cuidado personal",
  maquillaje: "Maquillaje",
};

const C: Record<string, ColorOption> = {
  blanco: { name: "Blanco", hex: "#f8fafc" },
  negro: { name: "Negro", hex: "#111827" },
  azul: { name: "Azul", hex: "#3B82F6" },
  celeste: { name: "Celeste", hex: "#38BDF8" },
  morado: { name: "Morado", hex: "#8B5CF6" },
  rosa: { name: "Rosa", hex: "#EC4899" },
  beige: { name: "Beige", hex: "#e7d8c3" },
  verde: { name: "Verde", hex: "#10b981" },
  gris: { name: "Gris", hex: "#9ca3af" },
  vino: { name: "Vino", hex: "#7f1d1d" },
  cafe: { name: "Café", hex: "#78350f" },
  dorado: { name: "Dorado", hex: "#d4af37" },
};

const img = (photoId: number) =>
  `https://images.pexels.com/photos/${photoId}/pexels-photo-${photoId}.jpeg?auto=compress&cs=tinysrgb&w=800&h=1000&fit=crop`;

export const ONE_SIZE = ["Única"];

export const NEW_PRODUCTS: Product[] = [
  {
    id: "p100",
    slug: "tenis-urban-classic-p100",
    name: "Tenis Urban Classic",
    description: "Tenis Urban Classic, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Tenis Urban Classic combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 499,
    image: img(2529148),
    images: [img(2529148)],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Tenis",
    style: "Urbano",
    material: "Textil y goma",
    availability: "Disponible en stock",
    colors: [C.blanco, C.negro],
    sizes: ["35", "36", "37", "38", "39", "40", "41", "42"],
    rating: 4.5,
    badge: "Nuevo",
  },
  {
    id: "p101",
    slug: "sneakers-retro-court-p101",
    name: "Sneakers Retro Court",
    description: "Sneakers Retro Court, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Sneakers Retro Court combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 549,
    image: img(1598505),
    images: [img(1598505)],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Sneakers",
    style: "Retro",
    material: "Cuero sintético y goma",
    availability: "Disponible en stock",
    colors: [C.blanco, C.verde],
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    rating: 4.6,
    badge: "Más vendido",
  },
  {
    id: "p102",
    slug: "zapatos-derby-essential-p102",
    name: "Zapatos Derby Essential",
    description: "Zapatos Derby Essential, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Zapatos Derby Essential combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 649,
    image: img(292999),
    images: [img(292999)],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Zapatos",
    style: "Formal",
    material: "Cuero sintético",
    availability: "Disponible en stock",
    colors: [C.negro, C.cafe],
    sizes: ["39", "40", "41", "42", "43"],
    rating: 4.7,
    badge: "Nuevo",
  },
  {
    id: "p103",
    slug: "mocasines-city-comfort-p103",
    name: "Mocasines City Comfort",
    description: "Mocasines City Comfort, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Mocasines City Comfort combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 579,
    image: img(267320),
    images: [img(267320)],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Mocasines",
    style: "Casual",
    material: "Cuero sintético",
    availability: "Disponible en stock",
    colors: [C.negro, C.cafe],
    sizes: ["36", "37", "38", "39", "40", "41"],
    rating: 4.8,
    badge: "Más vendido",
  },
  {
    id: "p104",
    slug: "botines-chelsea-nova-p104",
    name: "Botines Chelsea Nova",
    description: "Botines Chelsea Nova, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Botines Chelsea Nova combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 699,
    image: img(1306248),
    images: [img(1306248)],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Botines",
    style: "Minimalista",
    material: "Cuero sintético",
    availability: "Disponible en stock",
    colors: [C.negro, C.cafe],
    sizes: ["36", "37", "38", "39", "40", "41", "42"],
    rating: 4.9,
    badge: "Nuevo",
  },
  {
    id: "p105",
    slug: "sandalias-minimal-strap-p105",
    name: "Sandalias Minimal Strap",
    description: "Sandalias Minimal Strap, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Sandalias Minimal Strap combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 329,
    image: img(336372),
    images: [img(336372)],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Sandalias",
    style: "Minimalista",
    material: "Sintético",
    availability: "Disponible en stock",
    colors: [C.negro, C.beige],
    sizes: ["35", "36", "37", "38", "39", "40"],
    rating: 4.5,
    badge: "Nuevo",
  },
  {
    id: "p106",
    slug: "tenis-running-motion-p106",
    name: "Tenis Running Motion",
    description: "Tenis Running Motion, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Tenis Running Motion combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 599,
    image: img(1456706),
    images: [img(1456706)],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Tenis",
    style: "Deportivo",
    material: "Malla técnica y goma",
    availability: "Disponible en stock",
    colors: [C.negro, C.gris],
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    rating: 4.6,
    badge: "Más vendido",
  },
  {
    id: "p107",
    slug: "tenis-street-platform-p107",
    name: "Tenis Street Platform",
    description: "Tenis Street Platform, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Tenis Street Platform combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 529,
    image: img(1464625),
    images: [img(1464625)],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Tenis",
    style: "Streetwear",
    material: "Textil y goma",
    availability: "Disponible en stock",
    colors: [C.blanco, C.beige],
    sizes: ["35", "36", "37", "38", "39", "40"],
    rating: 4.7,
    badge: "Nuevo",
  },
  {
    id: "p108",
    slug: "botas-urban-track-p108",
    name: "Botas Urban Track",
    description: "Botas Urban Track, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Botas Urban Track combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 749,
    image: img(19090),
    images: [img(19090)],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Botas",
    style: "Urbano",
    material: "Sintético y goma",
    availability: "Disponible en stock",
    colors: [C.negro, C.gris],
    sizes: ["38", "39", "40", "41", "42", "43"],
    rating: 4.8,
    badge: "Nuevo",
  },
  {
    id: "p109",
    slug: "balerinas-soft-line-p109",
    name: "Balerinas Soft Line",
    description: "Balerinas Soft Line, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Balerinas Soft Line combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 349,
    image: img(985635),
    images: [img(985635)],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Balerinas",
    style: "Clásico",
    material: "Sintético",
    availability: "Disponible en stock",
    colors: [C.negro, C.beige],
    sizes: ["35", "36", "37", "38", "39", "40"],
    rating: 4.9,
    badge: undefined,
  },
  {
    id: "p110",
    slug: "camisa-oxford-premium-p110",
    name: "Camisa Oxford Premium",
    description: "Camisa Oxford Premium, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Camisa Oxford Premium combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 429,
    image: img(297933),
    images: [img(297933)],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Camisa",
    style: "Smart casual",
    material: "Algodón",
    availability: "Disponible en stock",
    colors: [C.blanco, C.azul],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
    badge: "Nuevo",
  },
  {
    id: "p111",
    slug: "pantalón-chino-tailored-p111",
    name: "Pantalón Chino Tailored",
    description: "Pantalón Chino Tailored, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Pantalón Chino Tailored combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 459,
    image: img(289753),
    images: [img(289753)],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Pantalón",
    style: "Smart casual",
    material: "Algodón stretch",
    availability: "Disponible en stock",
    colors: [C.beige, C.negro],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p112",
    slug: "chaqueta-bomber-city-p112",
    name: "Chaqueta Bomber City",
    description: "Chaqueta Bomber City, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Chaqueta Bomber City combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 649,
    image: img(1124465),
    images: [img(1124465)],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Chaqueta",
    style: "Urbano",
    material: "Poliéster",
    availability: "Disponible en stock",
    colors: [C.negro, C.verde],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
    badge: "Nuevo",
  },
  {
    id: "p113",
    slug: "polo-piqué-essential-p113",
    name: "Polo Piqué Essential",
    description: "Polo Piqué Essential, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Polo Piqué Essential combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 299,
    image: img(1043474),
    images: [img(1043474)],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Polo",
    style: "Casual",
    material: "Algodón piqué",
    availability: "Disponible en stock",
    colors: [C.blanco, C.azul],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.8,
    badge: "Más vendido",
  },
  {
    id: "p114",
    slug: "jeans-straight-indigo-p114",
    name: "Jeans Straight Indigo",
    description: "Jeans Straight Indigo, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Jeans Straight Indigo combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 499,
    image: img(1598507),
    images: [img(1598507)],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Jeans",
    style: "Casual",
    material: "Denim",
    availability: "Disponible en stock",
    colors: [C.azul, C.negro],
    sizes: ["28", "30", "32", "34", "36"],
    rating: 4.9,
    badge: undefined,
  },
  {
    id: "p115",
    slug: "sudadera-crewneck-core-p115",
    name: "Sudadera Crewneck Core",
    description: "Sudadera Crewneck Core, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Sudadera Crewneck Core combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 399,
    image: img(1183266),
    images: [img(1183266)],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Sudadera",
    style: "Casual",
    material: "Algodón fleece",
    availability: "Disponible en stock",
    colors: [C.gris, C.negro],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.5,
    badge: "Nuevo",
  },
  {
    id: "p116",
    slug: "vestido-midi-satinado-p116",
    name: "Vestido Midi Satinado",
    description: "Vestido Midi Satinado, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Vestido Midi Satinado combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 599,
    image: img(985635),
    images: [img(985635)],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Vestido",
    style: "Elegante",
    material: "Satén",
    availability: "Disponible en stock",
    colors: [C.vino, C.negro],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.6,
    badge: "Nuevo",
  },
  {
    id: "p117",
    slug: "blusa-manga-globo-p117",
    name: "Blusa Manga Globo",
    description: "Blusa Manga Globo, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Blusa Manga Globo combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 369,
    image: img(994523),
    images: [img(994523)],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Blusa",
    style: "Romántico",
    material: "Viscosa",
    availability: "Disponible en stock",
    colors: [C.blanco, C.rosa],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.7,
    badge: undefined,
  },
  {
    id: "p118",
    slug: "jeans-wide-leg-nova-p118",
    name: "Jeans Wide Leg Nova",
    description: "Jeans Wide Leg Nova, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Jeans Wide Leg Nova combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 529,
    image: img(1082529),
    images: [img(1082529)],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Jeans",
    style: "Contemporáneo",
    material: "Denim",
    availability: "Disponible en stock",
    colors: [C.azul, C.negro],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.8,
    badge: "Más vendido",
  },
  {
    id: "p119",
    slug: "blazer-estructurado-city-p119",
    name: "Blazer Estructurado City",
    description: "Blazer Estructurado City, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Blazer Estructurado City combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 699,
    image: img(1036623),
    images: [img(1036623)],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Blazer",
    style: "Elegante",
    material: "Poliéster y viscosa",
    availability: "Disponible en stock",
    colors: [C.negro, C.beige],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.9,
    badge: "Nuevo",
  },
  {
    id: "p120",
    slug: "falda-midi-plisada-p120",
    name: "Falda Midi Plisada",
    description: "Falda Midi Plisada, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Falda Midi Plisada combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 449,
    image: img(1755428),
    images: [img(1755428)],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Falda",
    style: "Elegante",
    material: "Poliéster",
    availability: "Disponible en stock",
    colors: [C.beige, C.negro],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p121",
    slug: "top-rib-essential-p121",
    name: "Top Rib Essential",
    description: "Top Rib Essential, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Top Rib Essential combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 249,
    image: img(2065195),
    images: [img(2065195)],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Top",
    style: "Casual",
    material: "Algodón elástico",
    availability: "Disponible en stock",
    colors: [C.blanco, C.negro],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.6,
    badge: "Nuevo",
  },
  {
    id: "p122",
    slug: "conjunto-kids-adventure-p122",
    name: "Conjunto Kids Adventure",
    description: "Conjunto Kids Adventure, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Conjunto Kids Adventure combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 389,
    image: img(1620760),
    images: [img(1620760)],
    category: "ninos",
    categoryLabel: CATEGORY_LABEL.ninos,
    type: "Conjunto",
    style: "Casual",
    material: "Algodón",
    availability: "Disponible en stock",
    colors: [C.azul, C.verde],
    sizes: ["4A", "6A", "8A", "10A", "12A"],
    rating: 4.7,
    badge: "Nuevo",
  },
  {
    id: "p123",
    slug: "sudadera-kids-graphic-p123",
    name: "Sudadera Kids Graphic",
    description: "Sudadera Kids Graphic, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Sudadera Kids Graphic combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 279,
    image: img(1619774),
    images: [img(1619774)],
    category: "ninos",
    categoryLabel: CATEGORY_LABEL.ninos,
    type: "Sudadera",
    style: "Urbano",
    material: "Algodón",
    availability: "Disponible en stock",
    colors: [C.gris, C.azul],
    sizes: ["4A", "6A", "8A", "10A", "12A"],
    rating: 4.8,
    badge: undefined,
  },
  {
    id: "p124",
    slug: "jeans-kids-flex-p124",
    name: "Jeans Kids Flex",
    description: "Jeans Kids Flex, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Jeans Kids Flex combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 299,
    image: img(1648377),
    images: [img(1648377)],
    category: "ninos",
    categoryLabel: CATEGORY_LABEL.ninos,
    type: "Jeans",
    style: "Casual",
    material: "Denim stretch",
    availability: "Disponible en stock",
    colors: [C.azul, C.negro],
    sizes: ["4A", "6A", "8A", "10A", "12A"],
    rating: 4.9,
    badge: "Más vendido",
  },
  {
    id: "p125",
    slug: "vestido-floral-mini-p125",
    name: "Vestido Floral Mini",
    description: "Vestido Floral Mini, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Vestido Floral Mini combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 349,
    image: img(3662667),
    images: [img(3662667)],
    category: "ninas",
    categoryLabel: CATEGORY_LABEL.ninas,
    type: "Vestido",
    style: "Casual",
    material: "Algodón",
    availability: "Disponible en stock",
    colors: [C.rosa, C.blanco],
    sizes: ["4A", "6A", "8A", "10A", "12A"],
    rating: 4.5,
    badge: "Nuevo",
  },
  {
    id: "p126",
    slug: "cardigan-soft-kids-p126",
    name: "Cardigan Soft Kids",
    description: "Cardigan Soft Kids, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Cardigan Soft Kids combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 299,
    image: img(3771643),
    images: [img(3771643)],
    category: "ninas",
    categoryLabel: CATEGORY_LABEL.ninas,
    type: "Cardigan",
    style: "Casual",
    material: "Tejido suave",
    availability: "Disponible en stock",
    colors: [C.rosa, C.beige],
    sizes: ["4A", "6A", "8A", "10A", "12A"],
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p127",
    slug: "falda-denim-kids-p127",
    name: "Falda Denim Kids",
    description: "Falda Denim Kids, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Falda Denim Kids combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 269,
    image: img(3771642),
    images: [img(3771642)],
    category: "ninas",
    categoryLabel: CATEGORY_LABEL.ninas,
    type: "Falda",
    style: "Casual",
    material: "Denim",
    availability: "Disponible en stock",
    colors: [C.azul, C.celeste],
    sizes: ["4A", "6A", "8A", "10A", "12A"],
    rating: 4.7,
    badge: "Nuevo",
  },
  {
    id: "p128",
    slug: "bolso-tote-everyday-p128",
    name: "Bolso Tote Everyday",
    description: "Bolso Tote Everyday, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Bolso Tote Everyday combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 549,
    image: img(1152077),
    images: [img(1152077)],
    category: "bolsos",
    categoryLabel: CATEGORY_LABEL.bolsos,
    type: "Bolso",
    style: "Casual",
    material: "Cuero sintético",
    availability: "Disponible en stock",
    colors: [C.negro, C.beige],
    sizes: ONE_SIZE,
    rating: 4.8,
    badge: "Más vendido",
  },
  {
    id: "p129",
    slug: "bolso-crossbody-mini-p129",
    name: "Bolso Crossbody Mini",
    description: "Bolso Crossbody Mini, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Bolso Crossbody Mini combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 429,
    image: img(904350),
    images: [img(904350)],
    category: "bolsos",
    categoryLabel: CATEGORY_LABEL.bolsos,
    type: "Bolso",
    style: "Minimalista",
    material: "Cuero sintético",
    availability: "Disponible en stock",
    colors: [C.negro, C.cafe],
    sizes: ONE_SIZE,
    rating: 4.9,
    badge: "Nuevo",
  },
  {
    id: "p130",
    slug: "mochila-city-compact-p130",
    name: "Mochila City Compact",
    description: "Mochila City Compact, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Mochila City Compact combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 499,
    image: img(2905238),
    images: [img(2905238)],
    category: "bolsos",
    categoryLabel: CATEGORY_LABEL.bolsos,
    type: "Mochila",
    style: "Urbano",
    material: "Nylon",
    availability: "Disponible en stock",
    colors: [C.negro, C.gris],
    sizes: ONE_SIZE,
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p131",
    slug: "aretes-hoop-dorados-p131",
    name: "Aretes Hoop Dorados",
    description: "Aretes Hoop Dorados, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Aretes Hoop Dorados combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 199,
    image: img(1454171),
    images: [img(1454171)],
    category: "joyeria",
    categoryLabel: CATEGORY_LABEL.joyeria,
    type: "Aretes",
    style: "Clásico",
    material: "Acero inoxidable",
    availability: "Disponible en stock",
    colors: [C.dorado],
    sizes: ONE_SIZE,
    rating: 4.6,
    badge: "Más vendido",
  },
  {
    id: "p132",
    slug: "collar-layered-nova-p132",
    name: "Collar Layered Nova",
    description: "Collar Layered Nova, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Collar Layered Nova combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 249,
    image: img(1191531),
    images: [img(1191531)],
    category: "joyeria",
    categoryLabel: CATEGORY_LABEL.joyeria,
    type: "Collar",
    style: "Contemporáneo",
    material: "Acero inoxidable",
    availability: "Disponible en stock",
    colors: [C.dorado],
    sizes: ONE_SIZE,
    rating: 4.7,
    badge: "Nuevo",
  },
  {
    id: "p133",
    slug: "pulsera-minimal-chain-p133",
    name: "Pulsera Minimal Chain",
    description: "Pulsera Minimal Chain, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Pulsera Minimal Chain combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 189,
    image: img(168927),
    images: [img(168927)],
    category: "joyeria",
    categoryLabel: CATEGORY_LABEL.joyeria,
    type: "Pulsera",
    style: "Minimalista",
    material: "Acero inoxidable",
    availability: "Disponible en stock",
    colors: [C.dorado],
    sizes: ONE_SIZE,
    rating: 4.8,
    badge: undefined,
  },
  {
    id: "p134",
    slug: "gorra-essential-logo-p134",
    name: "Gorra Essential Logo",
    description: "Gorra Essential Logo, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Gorra Essential Logo combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 199,
    image: img(1124465),
    images: [img(1124465)],
    category: "accesorios",
    categoryLabel: CATEGORY_LABEL.accesorios,
    type: "Gorra",
    style: "Urbano",
    material: "Algodón",
    availability: "Disponible en stock",
    colors: [C.negro, C.beige],
    sizes: ONE_SIZE,
    rating: 4.9,
    badge: "Nuevo",
  },
  {
    id: "p135",
    slug: "cinturón-classic-buckle-p135",
    name: "Cinturón Classic Buckle",
    description: "Cinturón Classic Buckle, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Cinturón Classic Buckle combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 249,
    image: img(89783),
    images: [img(89783)],
    category: "accesorios",
    categoryLabel: CATEGORY_LABEL.accesorios,
    type: "Cinturón",
    style: "Clásico",
    material: "Cuero sintético",
    availability: "Disponible en stock",
    colors: [C.negro, C.cafe],
    sizes: ["S", "M", "L"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p136",
    slug: "lentes-square-city-p136",
    name: "Lentes Square City",
    description: "Lentes Square City, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Lentes Square City combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 299,
    image: img(46710),
    images: [img(46710)],
    category: "accesorios",
    categoryLabel: CATEGORY_LABEL.accesorios,
    type: "Lentes",
    style: "Contemporáneo",
    material: "Acetato",
    availability: "Disponible en stock",
    colors: [C.negro, C.cafe],
    sizes: ONE_SIZE,
    rating: 4.6,
    badge: "Más vendido",
  },
  {
    id: "p137",
    slug: "eau-de-parfum-amber-night-p137",
    name: "Eau de Parfum Amber Night",
    description: "Eau de Parfum Amber Night, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Eau de Parfum Amber Night combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 499,
    image: img(965989),
    images: [img(965989)],
    category: "fragancias",
    categoryLabel: CATEGORY_LABEL.fragancias,
    type: "Perfume",
    style: "Oriental",
    material: "Fragancia 50 ml",
    availability: "Disponible en stock",
    colors: [C.dorado, C.negro],
    sizes: ONE_SIZE,
    rating: 4.7,
    badge: "Nuevo",
  },
  {
    id: "p138",
    slug: "eau-de-toilette-fresh-blue-p138",
    name: "Eau de Toilette Fresh Blue",
    description: "Eau de Toilette Fresh Blue, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Eau de Toilette Fresh Blue combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 449,
    image: img(1961792),
    images: [img(1961792)],
    category: "fragancias",
    categoryLabel: CATEGORY_LABEL.fragancias,
    type: "Perfume",
    style: "Fresco",
    material: "Fragancia 75 ml",
    availability: "Disponible en stock",
    colors: [C.azul, C.celeste],
    sizes: ONE_SIZE,
    rating: 4.8,
    badge: undefined,
  },
  {
    id: "p139",
    slug: "body-mist-floral-cloud-p139",
    name: "Body Mist Floral Cloud",
    description: "Body Mist Floral Cloud, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Body Mist Floral Cloud combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 229,
    image: img(1961782),
    images: [img(1961782)],
    category: "fragancias",
    categoryLabel: CATEGORY_LABEL.fragancias,
    type: "Body mist",
    style: "Floral",
    material: "Fragancia 120 ml",
    availability: "Disponible en stock",
    colors: [C.rosa, C.blanco],
    sizes: ONE_SIZE,
    rating: 4.9,
    badge: "Nuevo",
  },
  {
    id: "p140",
    slug: "sérum-niacinamida-balance-p140",
    name: "Sérum Niacinamida Balance",
    description: "Sérum Niacinamida Balance, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Sérum Niacinamida Balance combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 219,
    image: img(3762879),
    images: [img(3762879)],
    category: "skincare",
    categoryLabel: CATEGORY_LABEL.skincare,
    type: "Sérum",
    style: "Skincare",
    material: "Niacinamida",
    availability: "Disponible en stock",
    colors: [C.blanco, C.celeste],
    sizes: ONE_SIZE,
    rating: 4.5,
    badge: "Más vendido",
  },
  {
    id: "p141",
    slug: "crema-hidratante-barrier-p141",
    name: "Crema Hidratante Barrier",
    description: "Crema Hidratante Barrier, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Crema Hidratante Barrier combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 249,
    image: img(7796765),
    images: [img(7796765)],
    category: "skincare",
    categoryLabel: CATEGORY_LABEL.skincare,
    type: "Crema",
    style: "Skincare",
    material: "Ceramidas",
    availability: "Disponible en stock",
    colors: [C.blanco, C.beige],
    sizes: ONE_SIZE,
    rating: 4.6,
    badge: "Nuevo",
  },
  {
    id: "p142",
    slug: "limpiador-facial-gentle-p142",
    name: "Limpiador Facial Gentle",
    description: "Limpiador Facial Gentle, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Limpiador Facial Gentle combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 189,
    image: img(3737594),
    images: [img(3737594)],
    category: "skincare",
    categoryLabel: CATEGORY_LABEL.skincare,
    type: "Limpiador",
    style: "Skincare",
    material: "Gel facial",
    availability: "Disponible en stock",
    colors: [C.blanco, C.verde],
    sizes: ONE_SIZE,
    rating: 4.7,
    badge: undefined,
  },
  {
    id: "p143",
    slug: "protector-solar-daily-spf50-p143",
    name: "Protector Solar Daily SPF50",
    description: "Protector Solar Daily SPF50, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Protector Solar Daily SPF50 combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 279,
    image: img(3764014),
    images: [img(3764014)],
    category: "skincare",
    categoryLabel: CATEGORY_LABEL.skincare,
    type: "Protector solar",
    style: "Skincare",
    material: "Protección SPF50",
    availability: "Disponible en stock",
    colors: [C.blanco, C.beige],
    sizes: ONE_SIZE,
    rating: 4.8,
    badge: "Más vendido",
  },
  {
    id: "p144",
    slug: "gel-de-ducha-fresh-care-p144",
    name: "Gel de Ducha Fresh Care",
    description: "Gel de Ducha Fresh Care, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Gel de Ducha Fresh Care combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 169,
    image: img(6621462),
    images: [img(6621462)],
    category: "cuidado",
    categoryLabel: CATEGORY_LABEL.cuidado,
    type: "Cuidado corporal",
    style: "Cuidado personal",
    material: "Gel corporal",
    availability: "Disponible en stock",
    colors: [C.verde, C.blanco],
    sizes: ONE_SIZE,
    rating: 4.9,
    badge: undefined,
  },
  {
    id: "p145",
    slug: "loción-corporal-soft-skin-p145",
    name: "Loción Corporal Soft Skin",
    description: "Loción Corporal Soft Skin, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Loción Corporal Soft Skin combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 199,
    image: img(6621463),
    images: [img(6621463)],
    category: "cuidado",
    categoryLabel: CATEGORY_LABEL.cuidado,
    type: "Cuidado corporal",
    style: "Cuidado personal",
    material: "Loción hidratante",
    availability: "Disponible en stock",
    colors: [C.beige, C.blanco],
    sizes: ONE_SIZE,
    rating: 4.5,
    badge: "Nuevo",
  },
  {
    id: "p146",
    slug: "shampoo-daily-balance-p146",
    name: "Shampoo Daily Balance",
    description: "Shampoo Daily Balance, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Shampoo Daily Balance combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 179,
    image: img(3993449),
    images: [img(3993449)],
    category: "cuidado",
    categoryLabel: CATEGORY_LABEL.cuidado,
    type: "Cabello",
    style: "Cuidado personal",
    material: "Shampoo",
    availability: "Disponible en stock",
    colors: [C.verde, C.blanco],
    sizes: ONE_SIZE,
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p147",
    slug: "rubor-cream-blush-p147",
    name: "Rubor Cream Blush",
    description: "Rubor Cream Blush, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Rubor Cream Blush combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 189,
    image: img(2688991),
    images: [img(2688991)],
    category: "maquillaje",
    categoryLabel: CATEGORY_LABEL.maquillaje,
    type: "Rostro",
    style: "Maquillaje",
    material: "Rubor en crema",
    availability: "Disponible en stock",
    colors: [C.rosa, C.vino],
    sizes: ONE_SIZE,
    rating: 4.7,
    badge: "Nuevo",
  },
  {
    id: "p148",
    slug: "máscara-lash-definition-p148",
    name: "Máscara Lash Definition",
    description: "Máscara Lash Definition, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Máscara Lash Definition combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 179,
    image: img(3373746),
    images: [img(3373746)],
    category: "maquillaje",
    categoryLabel: CATEGORY_LABEL.maquillaje,
    type: "Ojos",
    style: "Maquillaje",
    material: "Máscara de pestañas",
    availability: "Disponible en stock",
    colors: [C.negro],
    sizes: ONE_SIZE,
    rating: 4.8,
    badge: "Más vendido",
  },
  {
    id: "p149",
    slug: "gloss-shine-lip-oil-p149",
    name: "Gloss Shine Lip Oil",
    description: "Gloss Shine Lip Oil, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Gloss Shine Lip Oil combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 159,
    image: img(2533266),
    images: [img(2533266)],
    category: "maquillaje",
    categoryLabel: CATEGORY_LABEL.maquillaje,
    type: "Labios",
    style: "Maquillaje",
    material: "Aceite labial",
    availability: "Disponible en stock",
    colors: [C.rosa, C.dorado],
    sizes: ONE_SIZE,
    rating: 4.9,
    badge: "Nuevo",
  },
  {
    id: "p150",
    slug: "base-skin-finish-p150",
    name: "Base Skin Finish",
    description: "Base Skin Finish, una opción versátil de la colección NOVASTYLE.",
    longDescription: "Base Skin Finish combina diseño actual, funcionalidad y una selección de materiales pensada para complementar el catálogo NOVASTYLE.",
    price: 259,
    image: img(2587175),
    images: [img(2587175)],
    category: "maquillaje",
    categoryLabel: CATEGORY_LABEL.maquillaje,
    type: "Rostro",
    style: "Maquillaje",
    material: "Base líquida",
    availability: "Disponible en stock",
    colors: [C.beige, C.cafe],
    sizes: ONE_SIZE,
    rating: 4.5,
    badge: undefined,
  },
];
