export type CategoryKey =
  | "hombre"
  | "mujer"
  | "ninos"
  | "ninas"
  | "calzado"
  | "bolsos"
  | "joyeria"
  | "accesorios"
  | "fragancias"
  | "skincare"
  | "cuidado"
  | "maquillaje";

export type ColorOption = { name: string; hex: string };

export type Product = {
  id: string;
  slug: string;
  name: string;
  description: string;
  longDescription: string;
  price: number;
  image: string;
  images: string[];
  category: CategoryKey;
  categoryLabel: string;
  type: string;
  style: string;
  material: string;
  availability: string;
  colors: ColorOption[];
  sizes: string[];
  rating: number;
  badge?: "Nuevo" | "Oferta" | "Más vendido";
};

const categoryFallbackVisual = (label: string) => {
  const safe = label.replace(/[&<>"']/g, "");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="750"><rect width="100%" height="100%" fill="#f5f5f4"/><text x="50%" y="48%" text-anchor="middle" font-family="Arial" font-size="34" fill="#292524">NOVASTYLE</text><text x="50%" y="55%" text-anchor="middle" font-family="Arial" font-size="22" fill="#78716c">${safe}</text></svg>`;
  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
};

/** Imagen local de respaldo por categoría. Se usa solo si una imagen real falla al cargar. */
export const FALLBACK_IMAGE: Record<CategoryKey, string> = {
  hombre: categoryFallbackVisual("Hombre"),
  mujer: categoryFallbackVisual("Mujer"),
  ninos: categoryFallbackVisual("Niños"),
  ninas: categoryFallbackVisual("Niñas"),
  calzado: categoryFallbackVisual("Calzado"),
  bolsos: categoryFallbackVisual("Bolsos"),
  joyeria: categoryFallbackVisual("Joyería"),
  accesorios: categoryFallbackVisual("Accesorios"),
  fragancias: categoryFallbackVisual("Fragancias"),
  skincare: categoryFallbackVisual("Skincare"),
  cuidado: categoryFallbackVisual("Cuidado personal"),
  maquillaje: categoryFallbackVisual("Maquillaje"),
};

export const CATEGORY_LABEL: Record<CategoryKey, string> = {
  hombre: "Hombre",
  mujer: "Mujer",
  ninos: "Niños",
  ninas: "Niñas",
  calzado: "Calzado",
  bolsos: "Bolsos",
  joyeria: "Joyería",
  accesorios: "Accesorios",
  fragancias: "Fragancias",
  skincare: "Skincare",
  cuidado: "Cuidado personal",
  maquillaje: "Maquillaje",
};

const C: Record<string, ColorOption> = {
  blanco: { name: "Blanco", hex: "#f8fafc" },
  negro: { name: "Negro", hex: "#111827" },
  azul: { name: "Azul", hex: "#3B82F6" },
  celeste: { name: "Celeste", hex: "#38BDF8" },
  morado: { name: "Morado", hex: "#8B5CF6" },
  rosa: { name: "Rosa", hex: "#EC4899" },
  beige: { name: "Beige", hex: "#e7d8c3" },
  verde: { name: "Verde", hex: "#10b981" },
  gris: { name: "Gris", hex: "#9ca3af" },
  vino: { name: "Vino", hex: "#7f1d1d" },
  cafe: { name: "Café", hex: "#78350f" },
  dorado: { name: "Dorado", hex: "#d4af37" },
};


export const ONE_SIZE = ["Única"];

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "hoodie-oversize-nova-p1",
    name: "Hoodie Oversize Nova",
    description: "Sudadera oversize de algodón premium con capucha forrada.",
    longDescription: "Sudadera oversize de algodón premium con capucha forrada. Confeccionada en 80% algodón, 20% poliéster, esta pieza de la línea urbano de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 349,
    image: "/product-images/p001.jpg",
    images: ["/product-images/p001.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Hoodies",
    style: "Urbano",
    material: "80% algodón, 20% poliéster",
    availability: "Últimas unidades",
    colors: [C.negro, C.gris, C.azul],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.8,
    badge: "Más vendido",
  },
  {
    id: "p2",
    slug: "camiseta-urban-basic-p2",
    name: "Camiseta Urban Basic",
    description: "Camiseta minimalista de corte relajado y tacto suave.",
    longDescription: "Camiseta minimalista de corte relajado y tacto suave. Confeccionada en 100% algodón peinado, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 189,
    image: "/product-images/p002.jpg",
    images: ["/product-images/p002.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Camisetas",
    style: "Casual",
    material: "100% algodón peinado",
    availability: "Disponible en stock",
    colors: [C.blanco, C.negro, C.celeste],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    badge: "Nuevo",
  },
  {
    id: "p3",
    slug: "chaqueta-denim-clasica-p3",
    name: "Chaqueta Denim Clásica",
    description: "Chaqueta de mezclilla lavado clásico con botones metálicos.",
    longDescription: "Chaqueta de mezclilla lavado clásico con botones metálicos. Confeccionada en 100% denim de algodón, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 499,
    image: "/product-images/p003.jpg",
    images: ["/product-images/p003.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Chaquetas",
    style: "Casual",
    material: "100% denim de algodón",
    availability: "Disponible en stock",
    colors: [C.azul, C.negro],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.9,
    badge: "Oferta",
  },
  {
    id: "p4",
    slug: "jeans-slim-indigo-p4",
    name: "Jeans Slim Índigo",
    description: "Jeans slim tiro medio con elastano para mayor comodidad.",
    longDescription: "Jeans slim tiro medio con elastano para mayor comodidad. Confeccionada en 98% algodón, 2% elastano, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 379,
    image: "/product-images/p004.jpg",
    images: ["/product-images/p004.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Jeans",
    style: "Casual",
    material: "98% algodón, 2% elastano",
    availability: "Disponible en stock",
    colors: [C.azul, C.negro, C.gris],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p5",
    slug: "bomber-satinada-p5",
    name: "Bomber Satinada",
    description: "Bomber satinada estilo streetwear con puños acanalados.",
    longDescription: "Bomber satinada estilo streetwear con puños acanalados. Confeccionada en poliéster satinado, esta pieza de la línea urbano de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 629,
    image: "/product-images/p005.jpg",
    images: ["/product-images/p005.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Chaquetas",
    style: "Urbano",
    material: "Poliéster satinado",
    availability: "Disponible en stock",
    colors: [C.negro, C.verde, C.vino],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    badge: "Nuevo",
  },
  {
    id: "p6",
    slug: "cargo-pants-utility-p6",
    name: "Cargo Pants Utility",
    description: "Pantalón cargo estilo utility con bolsillos laterales.",
    longDescription: "Pantalón cargo estilo utility con bolsillos laterales. Confeccionada en gabardina de algodón, esta pieza de la línea urbano de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 439,
    image: "/product-images/p006.jpg",
    images: ["/product-images/p006.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Pantalones",
    style: "Urbano",
    material: "Gabardina de algodón",
    availability: "Disponible en stock",
    colors: [C.beige, C.verde, C.negro],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p7",
    slug: "camisa-oxford-blanca-p7",
    name: "Camisa Oxford Blanca",
    description: "Camisa Oxford de corte regular ideal para ocasiones formales.",
    longDescription: "Camisa Oxford de corte regular ideal para ocasiones formales. Confeccionada en 100% algodón oxford, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 329,
    image: "/product-images/p007.jpg",
    images: ["/product-images/p007.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Camisas",
    style: "Elegante",
    material: "100% algodón Oxford",
    availability: "Disponible en stock",
    colors: [C.blanco, C.celeste],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    badge: undefined,
  },
  {
    id: "p8",
    slug: "polo-pique-nova-p8",
    name: "Polo Piqué Nova",
    description: "Polo de piqué con logo bordado y cuello estructurado.",
    longDescription: "Polo de piqué con logo bordado y cuello estructurado. Confeccionada en piqué de algodón, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 239,
    image: "/product-images/p008.jpg",
    images: ["/product-images/p008.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Polos",
    style: "Casual",
    material: "Piqué de algodón",
    availability: "Disponible en stock",
    colors: [C.azul, C.blanco, C.vino],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p9",
    slug: "jogger-tech-fleece-p9",
    name: "Jogger Tech Fleece",
    description: "Jogger deportivo de tejido térmico con puño elástico.",
    longDescription: "Jogger deportivo de tejido térmico con puño elástico. Confeccionada en fleece técnico reciclado, esta pieza de la línea deportivo de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 359,
    image: "/product-images/p009.jpg",
    images: ["/product-images/p009.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Joggers",
    style: "Deportivo",
    material: "Fleece técnico reciclado",
    availability: "Disponible en stock",
    colors: [C.gris, C.negro, C.azul],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    badge: "Más vendido",
  },
  {
    id: "p10",
    slug: "short-deportivo-runner-p10",
    name: "Short Deportivo Runner",
    description: "Short ligero de secado rápido con bolsillo oculto.",
    longDescription: "Short ligero de secado rápido con bolsillo oculto. Confeccionada en poliéster técnico, esta pieza de la línea deportivo de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 199,
    image: "/product-images/p010.jpg",
    images: ["/product-images/p010.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Shorts",
    style: "Deportivo",
    material: "Poliéster técnico",
    availability: "Disponible en stock",
    colors: [C.negro, C.azul],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.4,
    badge: undefined,
  },
  {
    id: "p11",
    slug: "sueter-tejido-nova-p11",
    name: "Suéter Tejido Nova",
    description: "Suéter tejido de punto fino, cuello redondo.",
    longDescription: "Suéter tejido de punto fino, cuello redondo. Confeccionada en mezcla lana-algodón, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 419,
    image: "/product-images/p011.jpg",
    images: ["/product-images/p011.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Suéteres",
    style: "Elegante",
    material: "Mezcla lana-algodón",
    availability: "Disponible en stock",
    colors: [C.beige, C.gris, C.vino],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p12",
    slug: "conjunto-sport-nova-p12",
    name: "Conjunto Sport Nova",
    description: "Conjunto deportivo de sudadera y pantalón a juego.",
    longDescription: "Conjunto deportivo de sudadera y pantalón a juego. Confeccionada en algodón french terry, esta pieza de la línea deportivo de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 599,
    image: "/product-images/p012.jpg",
    images: ["/product-images/p012.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Conjuntos",
    style: "Deportivo",
    material: "Algodón french terry",
    availability: "Últimas unidades",
    colors: [C.gris, C.negro],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.8,
    badge: "Nuevo",
  },
  {
    id: "p13",
    slug: "sudadera-crewneck-p13",
    name: "Sudadera Crewneck",
    description: "Sudadera cuello redondo con estampado minimalista.",
    longDescription: "Sudadera cuello redondo con estampado minimalista. Confeccionada en algodón french terry, esta pieza de la línea urbano de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 299,
    image: "/product-images/p013.jpg",
    images: ["/product-images/p013.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Sudaderas",
    style: "Urbano",
    material: "Algodón french terry",
    availability: "Disponible en stock",
    colors: [C.morado, C.negro, C.blanco],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p14",
    slug: "blazer-casual-slim-p14",
    name: "Blazer Casual Slim",
    description: "Blazer slim sin forro, perfecto para looks smart casual.",
    longDescription: "Blazer slim sin forro, perfecto para looks smart casual. Confeccionada en mezcla de lino y viscosa, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 789,
    image: "/product-images/p014.jpg",
    images: ["/product-images/p014.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Ropa elegante",
    style: "Elegante",
    material: "Mezcla de lino y viscosa",
    availability: "Disponible en stock",
    colors: [C.azul, C.beige],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.8,
    badge: undefined,
  },
  {
    id: "p15",
    slug: "chaqueta-puffer-hombre-p15",
    name: "Chaqueta Puffer Hombre",
    description: "Chaqueta acolchada ultraligera con relleno térmico.",
    longDescription: "Chaqueta acolchada ultraligera con relleno térmico. Confeccionada en nylon con relleno térmico, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 749,
    image: "/product-images/p015.jpg",
    images: ["/product-images/p015.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Chaquetas",
    style: "Casual",
    material: "Nylon con relleno térmico",
    availability: "Disponible en stock",
    colors: [C.negro, C.azul],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    badge: undefined,
  },
  {
    id: "p16",
    slug: "camisa-de-lino-fresca-p16",
    name: "Camisa de Lino Fresca",
    description: "Camisa de lino transpirable ideal para clima cálido.",
    longDescription: "Camisa de lino transpirable ideal para clima cálido. Confeccionada en 100% lino, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 349,
    image: "/product-images/p016.jpg",
    images: ["/product-images/p016.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Camisas",
    style: "Casual",
    material: "100% lino",
    availability: "Disponible en stock",
    colors: [C.blanco, C.beige, C.celeste],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p17",
    slug: "pantalon-chino-slim-p17",
    name: "Pantalón Chino Slim",
    description: "Pantalón chino de corte slim con acabado suave.",
    longDescription: "Pantalón chino de corte slim con acabado suave. Confeccionada en algodón elastizado, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 319,
    image: "/product-images/p017.jpg",
    images: ["/product-images/p017.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Pantalones",
    style: "Casual",
    material: "Algodón elastizado",
    availability: "Disponible en stock",
    colors: [C.beige, C.negro, C.azul],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p18",
    slug: "chaleco-acolchado-urbano-p18",
    name: "Chaleco Acolchado Urbano",
    description: "Chaleco acolchado sin mangas ideal para entretiempo.",
    longDescription: "Chaleco acolchado sin mangas ideal para entretiempo. Confeccionada en nylon acolchado, esta pieza de la línea urbano de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 389,
    image: "/product-images/p018.jpg",
    images: ["/product-images/p018.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Chaquetas",
    style: "Urbano",
    material: "Nylon acolchado",
    availability: "Disponible en stock",
    colors: [C.negro, C.verde],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.4,
    badge: undefined,
  },
  {
    id: "p19",
    slug: "traje-formal-dos-piezas-p19",
    name: "Traje Formal Dos Piezas",
    description: "Traje formal de corte moderno para ocasiones especiales.",
    longDescription: "Traje formal de corte moderno para ocasiones especiales. Confeccionada en lana mezclada, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 1290,
    image: "/product-images/p019.jpg",
    images: ["/product-images/p019.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Ropa elegante",
    style: "Elegante",
    material: "Lana mezclada",
    availability: "Disponible en stock",
    colors: [C.negro, C.gris],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.9,
    badge: "Nuevo",
  },
  {
    id: "p20",
    slug: "camiseta-estampada-streetwear-p20",
    name: "Camiseta Estampada Streetwear",
    description: "Camiseta con estampado gráfico de edición limitada.",
    longDescription: "Camiseta con estampado gráfico de edición limitada. Confeccionada en 100% algodón, esta pieza de la línea urbano de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 219,
    image: "/product-images/p020.jpg",
    images: ["/product-images/p020.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Camisetas",
    style: "Urbano",
    material: "100% algodón",
    availability: "Disponible en stock",
    colors: [C.negro, C.blanco],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p21",
    slug: "sudadera-zip-track-p21",
    name: "Sudadera Zip Track",
    description: "Sudadera con cierre y capucha, estilo deportivo retro.",
    longDescription: "Sudadera con cierre y capucha, estilo deportivo retro. Confeccionada en algodón mezclado, esta pieza de la línea deportivo de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 389,
    image: "/product-images/p021.jpg",
    images: ["/product-images/p021.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Sudaderas",
    style: "Deportivo",
    material: "Algodón mezclado",
    availability: "Disponible en stock",
    colors: [C.azul, C.gris, C.vino],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p22",
    slug: "pantalon-jogger-denim-p22",
    name: "Pantalón Jogger Denim",
    description: "Jogger de mezclilla con puño ajustado y bolsillos utilitarios.",
    longDescription: "Jogger de mezclilla con puño ajustado y bolsillos utilitarios. Confeccionada en denim elastizado, esta pieza de la línea urbano de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 429,
    image: "/product-images/p022.jpg",
    images: ["/product-images/p022.jpg"],
    category: "hombre",
    categoryLabel: CATEGORY_LABEL.hombre,
    type: "Jeans",
    style: "Urbano",
    material: "Denim elastizado",
    availability: "Disponible en stock",
    colors: [C.negro, C.azul],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p23",
    slug: "vestido-midi-elegante-p23",
    name: "Vestido Midi Elegante",
    description: "Vestido midi satinado de edición limitada.",
    longDescription: "Vestido midi satinado de edición limitada. Confeccionada en satén de viscosa, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 459,
    image: "/product-images/p023.jpg",
    images: ["/product-images/p023.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Vestidos",
    style: "Elegante",
    material: "Satén de viscosa",
    availability: "Últimas unidades",
    colors: [C.rosa, C.negro, C.morado],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.9,
    badge: "Nuevo",
  },
  {
    id: "p24",
    slug: "blusa-de-seda-perla-p24",
    name: "Blusa de Seda Perla",
    description: "Blusa de seda cuello V con caída fluida.",
    longDescription: "Blusa de seda cuello V con caída fluida. Confeccionada en seda satinada, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 429,
    image: "/product-images/p024.jpg",
    images: ["/product-images/p024.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Blusas",
    style: "Elegante",
    material: "Seda satinada",
    availability: "Disponible en stock",
    colors: [C.blanco, C.beige, C.celeste],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.8,
    badge: undefined,
  },
  {
    id: "p25",
    slug: "pantalon-wide-leg-p25",
    name: "Pantalón Wide Leg",
    description: "Pantalón wide leg fluido de caída premium.",
    longDescription: "Pantalón wide leg fluido de caída premium. Confeccionada en crepé de poliéster, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 389,
    image: "/product-images/p025.jpg",
    images: ["/product-images/p025.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Pantalones",
    style: "Elegante",
    material: "Crepé de poliéster",
    availability: "Disponible en stock",
    colors: [C.beige, C.negro, C.blanco],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    badge: "Nuevo",
  },
  {
    id: "p26",
    slug: "hoodie-cropped-nova-p26",
    name: "Hoodie Cropped Nova",
    description: "Hoodie corta con estampado exclusivo NOVASTYLE.",
    longDescription: "Hoodie corta con estampado exclusivo NOVASTYLE. Confeccionada en algodón french terry, esta pieza de la línea urbano de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 299,
    image: "/product-images/p026.jpg",
    images: ["/product-images/p026.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Hoodies",
    style: "Urbano",
    material: "Algodón french terry",
    availability: "Disponible en stock",
    colors: [C.rosa, C.morado, C.gris],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    badge: "Más vendido",
  },
  {
    id: "p27",
    slug: "puffer-jacket-mujer-p27",
    name: "Puffer Jacket Mujer",
    description: "Chaqueta acolchada ultraligera con capucha desmontable.",
    longDescription: "Chaqueta acolchada ultraligera con capucha desmontable. Confeccionada en nylon reciclado, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 749,
    image: "/product-images/p027.jpg",
    images: ["/product-images/p027.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Chaquetas",
    style: "Casual",
    material: "Nylon reciclado",
    availability: "Disponible en stock",
    colors: [C.blanco, C.negro, C.rosa],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    badge: undefined,
  },
  {
    id: "p28",
    slug: "mom-jeans-vintage-p28",
    name: "Mom Jeans Vintage",
    description: "Jeans tiro alto corte mom de lavado vintage.",
    longDescription: "Jeans tiro alto corte mom de lavado vintage. Confeccionada en 100% algodón denim, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 399,
    image: "/product-images/p028.jpg",
    images: ["/product-images/p028.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Jeans",
    style: "Casual",
    material: "100% algodón denim",
    availability: "Disponible en stock",
    colors: [C.azul, C.celeste],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.8,
    badge: "Más vendido",
  },
  {
    id: "p29",
    slug: "falda-plisada-midi-p29",
    name: "Falda Plisada Midi",
    description: "Falda plisada midi con cintura elástica.",
    longDescription: "Falda plisada midi con cintura elástica. Confeccionada en poliéster plisado, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 319,
    image: "/product-images/p029.jpg",
    images: ["/product-images/p029.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Faldas",
    style: "Elegante",
    material: "Poliéster plisado",
    availability: "Disponible en stock",
    colors: [C.negro, C.beige, C.morado],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p30",
    slug: "top-ribbed-basic-p30",
    name: "Top Ribbed Basic",
    description: "Top acanalado de tirantes, ajuste segunda piel.",
    longDescription: "Top acanalado de tirantes, ajuste segunda piel. Confeccionada en algodón acanalado, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 159,
    image: "/product-images/p030.jpg",
    images: ["/product-images/p030.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Tops",
    style: "Casual",
    material: "Algodón acanalado",
    availability: "Disponible en stock",
    colors: [C.blanco, C.negro, C.verde],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.4,
    badge: undefined,
  },
  {
    id: "p31",
    slug: "camiseta-boxy-fit-p31",
    name: "Camiseta Boxy Fit",
    description: "Camiseta de corte boxy con hombro caído.",
    longDescription: "Camiseta de corte boxy con hombro caído. Confeccionada en algodón orgánico, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 189,
    image: "/product-images/p031.jpg",
    images: ["/product-images/p031.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Camisetas",
    style: "Casual",
    material: "Algodón orgánico",
    availability: "Disponible en stock",
    colors: [C.blanco, C.celeste, C.rosa],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p32",
    slug: "short-denim-alto-p32",
    name: "Short Denim Alto",
    description: "Short de mezclilla tiro alto con deshilado.",
    longDescription: "Short de mezclilla tiro alto con deshilado. Confeccionada en denim de algodón, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 249,
    image: "/product-images/p032.jpg",
    images: ["/product-images/p032.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Shorts",
    style: "Casual",
    material: "Denim de algodón",
    availability: "Disponible en stock",
    colors: [C.azul, C.blanco],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p33",
    slug: "sudadera-colorblock-p33",
    name: "Sudadera Colorblock",
    description: "Sudadera colorblock inspirada en la paleta NOVA.",
    longDescription: "Sudadera colorblock inspirada en la paleta NOVA. Confeccionada en algodón mezclado, esta pieza de la línea urbano de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 329,
    image: "/product-images/p033.jpg",
    images: ["/product-images/p033.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Sudaderas",
    style: "Urbano",
    material: "Algodón mezclado",
    availability: "Disponible en stock",
    colors: [C.morado, C.celeste, C.rosa],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    badge: "Nuevo",
  },
  {
    id: "p34",
    slug: "chaqueta-denim-crop-p34",
    name: "Chaqueta Denim Crop",
    description: "Chaqueta de mezclilla corta con botones metálicos.",
    longDescription: "Chaqueta de mezclilla corta con botones metálicos. Confeccionada en denim rígido, esta pieza de la línea urbano de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 489,
    image: "/product-images/p034.jpg",
    images: ["/product-images/p034.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Chaquetas",
    style: "Urbano",
    material: "Denim rígido",
    availability: "Últimas unidades",
    colors: [C.azul, C.blanco],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p35",
    slug: "sueter-knit-suave-p35",
    name: "Suéter Knit Suave",
    description: "Suéter de punto suave con cuello alto.",
    longDescription: "Suéter de punto suave con cuello alto. Confeccionada en mezcla acrílico-lana, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 399,
    image: "/product-images/p035.jpg",
    images: ["/product-images/p035.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Suéteres",
    style: "Elegante",
    material: "Mezcla acrílico-lana",
    availability: "Disponible en stock",
    colors: [C.beige, C.rosa, C.gris],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    badge: undefined,
  },
  {
    id: "p36",
    slug: "conjunto-loungewear-p36",
    name: "Conjunto Loungewear",
    description: "Conjunto de top y pantalón en tejido suave.",
    longDescription: "Conjunto de top y pantalón en tejido suave. Confeccionada en modal y algodón, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 549,
    image: "/product-images/p036.jpg",
    images: ["/product-images/p036.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Conjuntos",
    style: "Casual",
    material: "Modal y algodón",
    availability: "Disponible en stock",
    colors: [C.beige, C.rosa],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.8,
    badge: "Nuevo",
  },
  {
    id: "p37",
    slug: "legging-sport-nova-p37",
    name: "Legging Sport Nova",
    description: "Legging deportivo de compresión con cintura alta.",
    longDescription: "Legging deportivo de compresión con cintura alta. Confeccionada en poliamida y elastano, esta pieza de la línea deportivo de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 279,
    image: "/product-images/p037.jpg",
    images: ["/product-images/p037.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Ropa deportiva",
    style: "Deportivo",
    material: "Poliamida y elastano",
    availability: "Disponible en stock",
    colors: [C.negro, C.morado, C.azul],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.8,
    badge: "Más vendido",
  },
  {
    id: "p38",
    slug: "blazer-estructurado-mujer-p38",
    name: "Blazer Estructurado Mujer",
    description: "Blazer estructurado ideal para looks de oficina.",
    longDescription: "Blazer estructurado ideal para looks de oficina. Confeccionada en mezcla de lana, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 649,
    image: "/product-images/p038.jpg",
    images: ["/product-images/p038.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Ropa elegante",
    style: "Elegante",
    material: "Mezcla de lana",
    availability: "Disponible en stock",
    colors: [C.negro, C.beige],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    badge: undefined,
  },
  {
    id: "p39",
    slug: "vestido-camisero-p39",
    name: "Vestido Camisero",
    description: "Vestido camisero de manga larga con cinturón.",
    longDescription: "Vestido camisero de manga larga con cinturón. Confeccionada en popelina de algodón, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 389,
    image: "/product-images/p039.jpg",
    images: ["/product-images/p039.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Vestidos",
    style: "Casual",
    material: "Popelina de algodón",
    availability: "Disponible en stock",
    colors: [C.blanco, C.celeste],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p40",
    slug: "blusa-manga-globo-p40",
    name: "Blusa Manga Globo",
    description: "Blusa con manga globo y cuello redondo.",
    longDescription: "Blusa con manga globo y cuello redondo. Confeccionada en viscosa fluida, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 319,
    image: "/product-images/p040.jpg",
    images: ["/product-images/p040.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Blusas",
    style: "Elegante",
    material: "Viscosa fluida",
    availability: "Disponible en stock",
    colors: [C.rosa, C.blanco],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p41",
    slug: "pantalon-palazzo-estampado-p41",
    name: "Pantalón Palazzo Estampado",
    description: "Pantalón palazzo de estampado floral y caída suave.",
    longDescription: "Pantalón palazzo de estampado floral y caída suave. Confeccionada en crepé estampado, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 349,
    image: "/product-images/p041.jpg",
    images: ["/product-images/p041.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Pantalones",
    style: "Elegante",
    material: "Crepé estampado",
    availability: "Disponible en stock",
    colors: [C.morado, C.rosa],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p42",
    slug: "cardigan-oversize-p42",
    name: "Cárdigan Oversize",
    description: "Cárdigan de punto oversize con botones frontales.",
    longDescription: "Cárdigan de punto oversize con botones frontales. Confeccionada en punto acrílico, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 429,
    image: "/product-images/p042.jpg",
    images: ["/product-images/p042.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Suéteres",
    style: "Casual",
    material: "Punto acrílico",
    availability: "Disponible en stock",
    colors: [C.beige, C.gris],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p43",
    slug: "falda-cargo-utility-p43",
    name: "Falda Cargo Utility",
    description: "Falda cargo con bolsillos laterales y cintura ajustable.",
    longDescription: "Falda cargo con bolsillos laterales y cintura ajustable. Confeccionada en gabardina de algodón, esta pieza de la línea urbano de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 299,
    image: "/product-images/p043.jpg",
    images: ["/product-images/p043.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Faldas",
    style: "Urbano",
    material: "Gabardina de algodón",
    availability: "Disponible en stock",
    colors: [C.verde, C.negro],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.4,
    badge: undefined,
  },
  {
    id: "p44",
    slug: "top-halter-verano-p44",
    name: "Top Halter Verano",
    description: "Top halter ligero ideal para looks de verano.",
    longDescription: "Top halter ligero ideal para looks de verano. Confeccionada en algodón ligero, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 179,
    image: "/product-images/p044.jpg",
    images: ["/product-images/p044.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Tops",
    style: "Casual",
    material: "Algodón ligero",
    availability: "Disponible en stock",
    colors: [C.celeste, C.blanco],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p45",
    slug: "chaqueta-trench-clasica-p45",
    name: "Chaqueta Trench Clásica",
    description: "Trench coat clásico de corte entallado.",
    longDescription: "Trench coat clásico de corte entallado. Confeccionada en gabardina impermeable, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 699,
    image: "/product-images/p045.jpg",
    images: ["/product-images/p045.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Chaquetas",
    style: "Elegante",
    material: "Gabardina impermeable",
    availability: "Últimas unidades",
    colors: [C.beige, C.negro],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.8,
    badge: undefined,
  },
  {
    id: "p46",
    slug: "jumpsuit-elegante-nova-p46",
    name: "Jumpsuit Elegante Nova",
    description: "Jumpsuit de una pieza con cinturón a juego.",
    longDescription: "Jumpsuit de una pieza con cinturón a juego. Confeccionada en crepé de poliéster, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 479,
    image: "/product-images/p046.jpg",
    images: ["/product-images/p046.jpg"],
    category: "mujer",
    categoryLabel: CATEGORY_LABEL.mujer,
    type: "Vestidos",
    style: "Elegante",
    material: "Crepé de poliéster",
    availability: "Disponible en stock",
    colors: [C.negro, C.vino],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    badge: undefined,
  },
  {
    id: "p47",
    slug: "playera-estampada-nino-p47",
    name: "Playera Estampada Niño",
    description: "Playera de algodón suave con estampado divertido.",
    longDescription: "Playera de algodón suave con estampado divertido. Confeccionada en 100% algodón, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 129,
    image: "/product-images/p047.jpg",
    images: ["/product-images/p047.jpg"],
    category: "ninos",
    categoryLabel: CATEGORY_LABEL.ninos,
    type: "Camisetas",
    style: "Casual",
    material: "100% algodón",
    availability: "Disponible en stock",
    colors: [C.azul, C.verde],
    sizes: ["2A", "4A", "6A", "8A", "10A", "12A"],
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p48",
    slug: "sudadera-con-capucha-nino-p48",
    name: "Sudadera con Capucha Niño",
    description: "Sudadera con capucha y bolsillo canguro para niño.",
    longDescription: "Sudadera con capucha y bolsillo canguro para niño. Confeccionada en algodón mezclado, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 199,
    image: "/product-images/p048.jpg",
    images: ["/product-images/p048.jpg"],
    category: "ninos",
    categoryLabel: CATEGORY_LABEL.ninos,
    type: "Sudaderas",
    style: "Casual",
    material: "Algodón mezclado",
    availability: "Disponible en stock",
    colors: [C.gris, C.azul],
    sizes: ["2A", "4A", "6A", "8A", "10A", "12A"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p49",
    slug: "short-deportivo-nino-p49",
    name: "Short Deportivo Niño",
    description: "Short deportivo transpirable para actividades al aire libre.",
    longDescription: "Short deportivo transpirable para actividades al aire libre. Confeccionada en poliéster técnico, esta pieza de la línea deportivo de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 99,
    image: "/product-images/p049.jpg",
    images: ["/product-images/p049.jpg"],
    category: "ninos",
    categoryLabel: CATEGORY_LABEL.ninos,
    type: "Shorts",
    style: "Deportivo",
    material: "Poliéster técnico",
    availability: "Disponible en stock",
    colors: [C.azul, C.negro],
    sizes: ["2A", "4A", "6A", "8A", "10A", "12A"],
    rating: 4.4,
    badge: undefined,
  },
  {
    id: "p50",
    slug: "chaqueta-ligera-nino-p50",
    name: "Chaqueta Ligera Niño",
    description: "Chaqueta ligera resistente al viento para uso diario.",
    longDescription: "Chaqueta ligera resistente al viento para uso diario. Confeccionada en nylon ligero, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 249,
    image: "/product-images/p050.jpg",
    images: ["/product-images/p050.jpg"],
    category: "ninos",
    categoryLabel: CATEGORY_LABEL.ninos,
    type: "Chaquetas",
    style: "Casual",
    material: "Nylon ligero",
    availability: "Disponible en stock",
    colors: [C.negro, C.verde],
    sizes: ["2A", "4A", "6A", "8A", "10A", "12A"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p51",
    slug: "conjunto-casual-nino-p51",
    name: "Conjunto Casual Niño",
    description: "Conjunto de camiseta y short a juego.",
    longDescription: "Conjunto de camiseta y short a juego. Confeccionada en algodón suave, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 179,
    image: "/product-images/p051.jpg",
    images: ["/product-images/p051.jpg"],
    category: "ninos",
    categoryLabel: CATEGORY_LABEL.ninos,
    type: "Conjuntos",
    style: "Casual",
    material: "Algodón suave",
    availability: "Disponible en stock",
    colors: [C.celeste, C.blanco],
    sizes: ["2A", "4A", "6A", "8A", "10A", "12A"],
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p52",
    slug: "pantalon-jogger-nino-p52",
    name: "Pantalón Jogger Niño",
    description: "Jogger cómodo de cintura elástica para niño.",
    longDescription: "Jogger cómodo de cintura elástica para niño. Confeccionada en algodón french terry, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 149,
    image: "/product-images/p052.jpg",
    images: ["/product-images/p052.jpg"],
    category: "ninos",
    categoryLabel: CATEGORY_LABEL.ninos,
    type: "Pantalones",
    style: "Casual",
    material: "Algodón french terry",
    availability: "Disponible en stock",
    colors: [C.gris, C.negro],
    sizes: ["2A", "4A", "6A", "8A", "10A", "12A"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p53",
    slug: "camisa-casual-nino-p53",
    name: "Camisa Casual Niño",
    description: "Camisa de manga corta ideal para ocasiones especiales.",
    longDescription: "Camisa de manga corta ideal para ocasiones especiales. Confeccionada en algodón popelina, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 159,
    image: "/product-images/p053.jpg",
    images: ["/product-images/p053.jpg"],
    category: "ninos",
    categoryLabel: CATEGORY_LABEL.ninos,
    type: "Camisas",
    style: "Elegante",
    material: "Algodón popelina",
    availability: "Disponible en stock",
    colors: [C.blanco, C.celeste],
    sizes: ["2A", "4A", "6A", "8A", "10A", "12A"],
    rating: 4.4,
    badge: undefined,
  },
  {
    id: "p54",
    slug: "sueter-tejido-nino-p54",
    name: "Suéter Tejido Niño",
    description: "Suéter tejido cálido de cuello redondo para niño.",
    longDescription: "Suéter tejido cálido de cuello redondo para niño. Confeccionada en mezcla acrílica, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 189,
    image: "/product-images/p054.jpg",
    images: ["/product-images/p054.jpg"],
    category: "ninos",
    categoryLabel: CATEGORY_LABEL.ninos,
    type: "Suéteres",
    style: "Casual",
    material: "Mezcla acrílica",
    availability: "Disponible en stock",
    colors: [C.azul, C.gris],
    sizes: ["2A", "4A", "6A", "8A", "10A", "12A"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p55",
    slug: "vestido-floral-nina-p55",
    name: "Vestido Floral Niña",
    description: "Vestido floral de algodón fresco para uso diario.",
    longDescription: "Vestido floral de algodón fresco para uso diario. Confeccionada en 100% algodón, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 189,
    image: "/product-images/p055.jpg",
    images: ["/product-images/p055.jpg"],
    category: "ninas",
    categoryLabel: CATEGORY_LABEL.ninas,
    type: "Vestidos",
    style: "Casual",
    material: "100% algodón",
    availability: "Disponible en stock",
    colors: [C.rosa, C.blanco],
    sizes: ["2A", "4A", "6A", "8A", "10A", "12A"],
    rating: 4.7,
    badge: undefined,
  },
  {
    id: "p56",
    slug: "sudadera-estampada-nina-p56",
    name: "Sudadera Estampada Niña",
    description: "Sudadera suave con estampado juguetón.",
    longDescription: "Sudadera suave con estampado juguetón. Confeccionada en algodón mezclado, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 199,
    image: "/product-images/p056.jpg",
    images: ["/product-images/p056.jpg"],
    category: "ninas",
    categoryLabel: CATEGORY_LABEL.ninas,
    type: "Sudaderas",
    style: "Casual",
    material: "Algodón mezclado",
    availability: "Últimas unidades",
    colors: [C.rosa, C.morado],
    sizes: ["2A", "4A", "6A", "8A", "10A", "12A"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p57",
    slug: "falda-plisada-nina-p57",
    name: "Falda Plisada Niña",
    description: "Falda plisada cómoda con cintura elástica.",
    longDescription: "Falda plisada cómoda con cintura elástica. Confeccionada en poliéster plisado, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 149,
    image: "/product-images/p057.jpg",
    images: ["/product-images/p057.jpg"],
    category: "ninas",
    categoryLabel: CATEGORY_LABEL.ninas,
    type: "Faldas",
    style: "Casual",
    material: "Poliéster plisado",
    availability: "Disponible en stock",
    colors: [C.rosa, C.celeste],
    sizes: ["2A", "4A", "6A", "8A", "10A", "12A"],
    rating: 4.4,
    badge: undefined,
  },
  {
    id: "p58",
    slug: "conjunto-casual-nina-p58",
    name: "Conjunto Casual Niña",
    description: "Conjunto de blusa y short a juego.",
    longDescription: "Conjunto de blusa y short a juego. Confeccionada en algodón suave, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 179,
    image: "/product-images/p058.jpg",
    images: ["/product-images/p058.jpg"],
    category: "ninas",
    categoryLabel: CATEGORY_LABEL.ninas,
    type: "Conjuntos",
    style: "Casual",
    material: "Algodón suave",
    availability: "Disponible en stock",
    colors: [C.rosa, C.blanco],
    sizes: ["2A", "4A", "6A", "8A", "10A", "12A"],
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p59",
    slug: "camiseta-estampada-nina-p59",
    name: "Camiseta Estampada Niña",
    description: "Camiseta de algodón con estampado colorido.",
    longDescription: "Camiseta de algodón con estampado colorido. Confeccionada en 100% algodón, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 119,
    image: "/product-images/p059.jpg",
    images: ["/product-images/p059.jpg"],
    category: "ninas",
    categoryLabel: CATEGORY_LABEL.ninas,
    type: "Camisetas",
    style: "Casual",
    material: "100% algodón",
    availability: "Disponible en stock",
    colors: [C.rosa, C.celeste],
    sizes: ["2A", "4A", "6A", "8A", "10A", "12A"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p60",
    slug: "chaqueta-ligera-nina-p60",
    name: "Chaqueta Ligera Niña",
    description: "Chaqueta ligera con capucha para días frescos.",
    longDescription: "Chaqueta ligera con capucha para días frescos. Confeccionada en nylon ligero, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 239,
    image: "/product-images/p060.jpg",
    images: ["/product-images/p060.jpg"],
    category: "ninas",
    categoryLabel: CATEGORY_LABEL.ninas,
    type: "Chaquetas",
    style: "Casual",
    material: "Nylon ligero",
    availability: "Disponible en stock",
    colors: [C.rosa, C.morado],
    sizes: ["2A", "4A", "6A", "8A", "10A", "12A"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p61",
    slug: "legging-estampado-nina-p61",
    name: "Legging Estampado Niña",
    description: "Legging cómodo de estampado divertido.",
    longDescription: "Legging cómodo de estampado divertido. Confeccionada en algodón elastizado, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 99,
    image: "/product-images/p061.jpg",
    images: ["/product-images/p061.jpg"],
    category: "ninas",
    categoryLabel: CATEGORY_LABEL.ninas,
    type: "Pantalones",
    style: "Casual",
    material: "Algodón elastizado",
    availability: "Disponible en stock",
    colors: [C.rosa, C.morado],
    sizes: ["2A", "4A", "6A", "8A", "10A", "12A"],
    rating: 4.4,
    badge: undefined,
  },
  {
    id: "p62",
    slug: "sueter-tejido-nina-p62",
    name: "Suéter Tejido Niña",
    description: "Suéter tejido suave de cuello redondo para niña.",
    longDescription: "Suéter tejido suave de cuello redondo para niña. Confeccionada en mezcla acrílica, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 179,
    image: "/product-images/p062.jpg",
    images: ["/product-images/p062.jpg"],
    category: "ninas",
    categoryLabel: CATEGORY_LABEL.ninas,
    type: "Suéteres",
    style: "Casual",
    material: "Mezcla acrílica",
    availability: "Disponible en stock",
    colors: [C.rosa, C.beige],
    sizes: ["2A", "4A", "6A", "8A", "10A", "12A"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p63",
    slug: "sneakers-urban-nova-p63",
    name: "Sneakers Urban Nova",
    description: "Sneakers de estilo urbano con suela ligera.",
    longDescription: "Sneakers de estilo urbano con suela ligera. Confeccionada en malla y sintético, esta pieza de la línea urbano de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 459,
    image: "/product-images/p063.jpg",
    images: ["/product-images/p063.jpg"],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Zapatillas",
    style: "Urbano",
    material: "Malla y sintético",
    availability: "Disponible en stock",
    colors: [C.blanco, C.negro],
    sizes: ["35", "36", "37", "38", "39", "40", "41", "42", "43"],
    rating: 4.7,
    badge: "Más vendido",
  },
  {
    id: "p64",
    slug: "botas-cuero-clasicas-p64",
    name: "Botas Cuero Clásicas",
    description: "Botas de cuero genuino con acabado clásico.",
    longDescription: "Botas de cuero genuino con acabado clásico. Confeccionada en cuero genuino, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 699,
    image: "/product-images/p064.jpg",
    images: ["/product-images/p064.jpg"],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Botas",
    style: "Elegante",
    material: "Cuero genuino",
    availability: "Disponible en stock",
    colors: [C.negro, C.cafe],
    sizes: ["35", "36", "37", "38", "39", "40", "41", "42", "43"],
    rating: 4.8,
    badge: undefined,
  },
  {
    id: "p65",
    slug: "zapato-formal-oxford-p65",
    name: "Zapato Formal Oxford",
    description: "Zapato formal tipo Oxford para ocasiones elegantes.",
    longDescription: "Zapato formal tipo Oxford para ocasiones elegantes. Confeccionada en cuero sintético, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 649,
    image: "/product-images/p065.jpg",
    images: ["/product-images/p065.jpg"],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Formales",
    style: "Elegante",
    material: "Cuero sintético",
    availability: "Disponible en stock",
    colors: [C.negro, C.cafe],
    sizes: ["35", "36", "37", "38", "39", "40", "41", "42", "43"],
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p66",
    slug: "sandalias-verano-nova-p66",
    name: "Sandalias Verano Nova",
    description: "Sandalias ligeras ideales para el verano.",
    longDescription: "Sandalias ligeras ideales para el verano. Confeccionada en sintético y goma, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 259,
    image: "/product-images/p066.jpg",
    images: ["/product-images/p066.jpg"],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Sandalias",
    style: "Casual",
    material: "Sintético y goma",
    availability: "Disponible en stock",
    colors: [C.beige, C.negro],
    sizes: ["35", "36", "37", "38", "39", "40", "41", "42", "43"],
    rating: 4.4,
    badge: undefined,
  },
  {
    id: "p67",
    slug: "sneakers-running-pro-p67",
    name: "Sneakers Running Pro",
    description: "Sneakers deportivos con amortiguación reforzada.",
    longDescription: "Sneakers deportivos con amortiguación reforzada. Confeccionada en malla técnica, esta pieza de la línea deportivo de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 549,
    image: "/product-images/p067.jpg",
    images: ["/product-images/p067.jpg"],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Zapatillas",
    style: "Deportivo",
    material: "Malla técnica",
    availability: "Últimas unidades",
    colors: [C.negro, C.azul],
    sizes: ["35", "36", "37", "38", "39", "40", "41", "42", "43"],
    rating: 4.7,
    badge: undefined,
  },
  {
    id: "p68",
    slug: "mocasines-casuales-p68",
    name: "Mocasines Casuales",
    description: "Mocasines cómodos de estilo casual chic.",
    longDescription: "Mocasines cómodos de estilo casual chic. Confeccionada en cuero sintético, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 399,
    image: "/product-images/p068.jpg",
    images: ["/product-images/p068.jpg"],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Formales",
    style: "Casual",
    material: "Cuero sintético",
    availability: "Disponible en stock",
    colors: [C.cafe, C.negro],
    sizes: ["35", "36", "37", "38", "39", "40", "41", "42", "43"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p69",
    slug: "botines-chelsea-nova-p69",
    name: "Botines Chelsea Nova",
    description: "Botines estilo Chelsea con elástico lateral.",
    longDescription: "Botines estilo Chelsea con elástico lateral. Confeccionada en cuero sintético, esta pieza de la línea urbano de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 479,
    image: "/product-images/p069.jpg",
    images: ["/product-images/p069.jpg"],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Botas",
    style: "Urbano",
    material: "Cuero sintético",
    availability: "Disponible en stock",
    colors: [C.negro, C.cafe],
    sizes: ["35", "36", "37", "38", "39", "40", "41", "42", "43"],
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p70",
    slug: "sneakers-plataforma-mujer-p70",
    name: "Sneakers Plataforma Mujer",
    description: "Sneakers con plataforma para un look moderno.",
    longDescription: "Sneakers con plataforma para un look moderno. Confeccionada en sintético y goma, esta pieza de la línea urbano de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 519,
    image: "/product-images/p070.jpg",
    images: ["/product-images/p070.jpg"],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Zapatillas",
    style: "Urbano",
    material: "Sintético y goma",
    availability: "Disponible en stock",
    colors: [C.blanco, C.rosa],
    sizes: ["35", "36", "37", "38", "39", "40", "41", "42", "43"],
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p71",
    slug: "zapatos-deportivos-nino-p71",
    name: "Zapatos Deportivos Niño",
    description: "Zapatos deportivos cómodos para uso diario infantil.",
    longDescription: "Zapatos deportivos cómodos para uso diario infantil. Confeccionada en malla y goma, esta pieza de la línea deportivo de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 229,
    image: "/product-images/p071.jpg",
    images: ["/product-images/p071.jpg"],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Infantil",
    style: "Deportivo",
    material: "Malla y goma",
    availability: "Disponible en stock",
    colors: [C.azul, C.negro],
    sizes: ["35", "36", "37", "38", "39", "40", "41", "42", "43"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p72",
    slug: "sandalias-trekking-outdoor-p72",
    name: "Sandalias Trekking Outdoor",
    description: "Sandalias resistentes para actividades al aire libre.",
    longDescription: "Sandalias resistentes para actividades al aire libre. Confeccionada en sintético resistente, esta pieza de la línea deportivo de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 349,
    image: "/product-images/p072.jpg",
    images: ["/product-images/p072.jpg"],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Sandalias",
    style: "Deportivo",
    material: "Sintético resistente",
    availability: "Disponible en stock",
    colors: [C.negro, C.verde],
    sizes: ["35", "36", "37", "38", "39", "40", "41", "42", "43"],
    rating: 4.4,
    badge: undefined,
  },
  {
    id: "p73",
    slug: "tenis-skate-clasico-p73",
    name: "Tenis Skate Clásico",
    description: "Tenis de skate con suela vulcanizada resistente.",
    longDescription: "Tenis de skate con suela vulcanizada resistente. Confeccionada en lona y goma, esta pieza de la línea urbano de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 399,
    image: "/product-images/p073.jpg",
    images: ["/product-images/p073.jpg"],
    category: "calzado",
    categoryLabel: CATEGORY_LABEL.calzado,
    type: "Zapatillas",
    style: "Urbano",
    material: "Lona y goma",
    availability: "Disponible en stock",
    colors: [C.blanco, C.negro],
    sizes: ["35", "36", "37", "38", "39", "40", "41", "42", "43"],
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p74",
    slug: "bolso-tote-cuero-nova-p74",
    name: "Bolso Tote Cuero Nova",
    description: "Bolso tote espacioso de cuero sintético premium.",
    longDescription: "Bolso tote espacioso de cuero sintético premium. Confeccionada en cuero sintético, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 459,
    image: "/product-images/p074.jpg",
    images: ["/product-images/p074.jpg"],
    category: "bolsos",
    categoryLabel: CATEGORY_LABEL.bolsos,
    type: "Bolsos",
    style: "Elegante",
    material: "Cuero sintético",
    availability: "Disponible en stock",
    colors: [C.negro, C.cafe],
    sizes: ONE_SIZE,
    rating: 4.7,
    badge: "Más vendido",
  },
  {
    id: "p75",
    slug: "bolso-crossbody-urbano-p75",
    name: "Bolso Crossbody Urbano",
    description: "Bolso crossbody compacto ideal para el día a día.",
    longDescription: "Bolso crossbody compacto ideal para el día a día. Confeccionada en sintético resistente, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 329,
    image: "/product-images/p075.jpg",
    images: ["/product-images/p075.jpg"],
    category: "bolsos",
    categoryLabel: CATEGORY_LABEL.bolsos,
    type: "Bolsos",
    style: "Casual",
    material: "Sintético resistente",
    availability: "Disponible en stock",
    colors: [C.negro, C.beige],
    sizes: ONE_SIZE,
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p76",
    slug: "mochila-urbana-nova-p76",
    name: "Mochila Urbana Nova",
    description: "Mochila urbana con compartimento para laptop.",
    longDescription: "Mochila urbana con compartimento para laptop. Confeccionada en nylon resistente, esta pieza de la línea urbano de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 399,
    image: "/product-images/p076.jpg",
    images: ["/product-images/p076.jpg"],
    category: "bolsos",
    categoryLabel: CATEGORY_LABEL.bolsos,
    type: "Mochilas",
    style: "Urbano",
    material: "Nylon resistente",
    availability: "Disponible en stock",
    colors: [C.negro, C.gris],
    sizes: ONE_SIZE,
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p77",
    slug: "bolso-de-mano-elegante-p77",
    name: "Bolso de Mano Elegante",
    description: "Bolso de mano compacto para ocasiones especiales.",
    longDescription: "Bolso de mano compacto para ocasiones especiales. Confeccionada en sintético satinado, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 379,
    image: "/product-images/p077.jpg",
    images: ["/product-images/p077.jpg"],
    category: "bolsos",
    categoryLabel: CATEGORY_LABEL.bolsos,
    type: "Bolsos",
    style: "Elegante",
    material: "Sintético satinado",
    availability: "Disponible en stock",
    colors: [C.negro, C.dorado],
    sizes: ONE_SIZE,
    rating: 4.7,
    badge: undefined,
  },
  {
    id: "p78",
    slug: "bolso-bandolera-casual-p78",
    name: "Bolso Bandolera Casual",
    description: "Bolso bandolera versátil para uso diario.",
    longDescription: "Bolso bandolera versátil para uso diario. Confeccionada en cuero sintético, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 289,
    image: "/product-images/p078.jpg",
    images: ["/product-images/p078.jpg"],
    category: "bolsos",
    categoryLabel: CATEGORY_LABEL.bolsos,
    type: "Bolsos",
    style: "Casual",
    material: "Cuero sintético",
    availability: "Últimas unidades",
    colors: [C.cafe, C.beige],
    sizes: ONE_SIZE,
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p79",
    slug: "set-aretes-dorados-nova-p79",
    name: "Set Aretes Dorados Nova",
    description: "Set de aretes bañados en oro de diseño minimalista.",
    longDescription: "Set de aretes bañados en oro de diseño minimalista. Confeccionada en baño de oro, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 189,
    image: "/product-images/p079.jpg",
    images: ["/product-images/p079.jpg"],
    category: "joyeria",
    categoryLabel: CATEGORY_LABEL.joyeria,
    type: "Joyería",
    style: "Elegante",
    material: "Baño de oro",
    availability: "Disponible en stock",
    colors: [C.dorado],
    sizes: ONE_SIZE,
    rating: 4.7,
    badge: undefined,
  },
  {
    id: "p80",
    slug: "collar-cadena-fina-p80",
    name: "Collar Cadena Fina",
    description: "Collar de cadena fina bañada en oro para uso diario.",
    longDescription: "Collar de cadena fina bañada en oro para uso diario. Confeccionada en baño de oro, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 219,
    image: "/product-images/p080.jpg",
    images: ["/product-images/p080.jpg"],
    category: "joyeria",
    categoryLabel: CATEGORY_LABEL.joyeria,
    type: "Joyería",
    style: "Elegante",
    material: "Baño de oro",
    availability: "Disponible en stock",
    colors: [C.dorado],
    sizes: ONE_SIZE,
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p81",
    slug: "pulsera-bangle-dorada-p81",
    name: "Pulsera Bangle Dorada",
    description: "Pulsera tipo bangle de acabado dorado brillante.",
    longDescription: "Pulsera tipo bangle de acabado dorado brillante. Confeccionada en baño de oro, esta pieza de la línea elegante de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 169,
    image: "/product-images/p081.jpg",
    images: ["/product-images/p081.jpg"],
    category: "joyeria",
    categoryLabel: CATEGORY_LABEL.joyeria,
    type: "Joyería",
    style: "Elegante",
    material: "Baño de oro",
    availability: "Disponible en stock",
    colors: [C.dorado],
    sizes: ONE_SIZE,
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p82",
    slug: "lentes-de-sol-aviador-p82",
    name: "Lentes de Sol Aviador",
    description: "Lentes de sol estilo aviador con protección UV.",
    longDescription: "Lentes de sol estilo aviador con protección UV. Confeccionada en metal y policarbonato, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 249,
    image: "/product-images/p082.jpg",
    images: ["/product-images/p082.jpg"],
    category: "accesorios",
    categoryLabel: CATEGORY_LABEL.accesorios,
    type: "Accesorios",
    style: "Casual",
    material: "Metal y policarbonato",
    availability: "Disponible en stock",
    colors: [C.negro, C.dorado],
    sizes: ONE_SIZE,
    rating: 4.6,
    badge: "Nuevo",
  },
  {
    id: "p83",
    slug: "lentes-de-sol-redondos-p83",
    name: "Lentes de Sol Redondos",
    description: "Lentes de sol de montura redonda estilo retro.",
    longDescription: "Lentes de sol de montura redonda estilo retro. Confeccionada en acetato, esta pieza de la línea urbano de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 229,
    image: "/product-images/p083.jpg",
    images: ["/product-images/p083.jpg"],
    category: "accesorios",
    categoryLabel: CATEGORY_LABEL.accesorios,
    type: "Accesorios",
    style: "Urbano",
    material: "Acetato",
    availability: "Disponible en stock",
    colors: [C.negro, C.cafe],
    sizes: ONE_SIZE,
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p84",
    slug: "set-lentes-de-sol-nova-p84",
    name: "Set Lentes de Sol Nova",
    description: "Set de lentes de sol de exhibición con estuche.",
    longDescription: "Set de lentes de sol de exhibición con estuche. Confeccionada en acetato y metal, esta pieza de la línea casual de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 279,
    image: "/product-images/p084.jpg",
    images: ["/product-images/p084.jpg"],
    category: "accesorios",
    categoryLabel: CATEGORY_LABEL.accesorios,
    type: "Accesorios",
    style: "Casual",
    material: "Acetato y metal",
    availability: "Disponible en stock",
    colors: [C.negro, C.dorado],
    sizes: ONE_SIZE,
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p85",
    slug: "nova-homme-eau-de-parfum-p85",
    name: "Nova Homme Eau de Parfum",
    description: "Fragancia masculina de notas amaderadas y cítricas.",
    longDescription: "Fragancia masculina de notas amaderadas y cítricas. Confeccionada en eau de parfum, esta pieza de la línea fragancias de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 399,
    image: "/product-images/p085.jpg",
    images: ["/product-images/p085.jpg"],
    category: "fragancias",
    categoryLabel: CATEGORY_LABEL.fragancias,
    type: "Fragancias",
    style: "Fragancias",
    material: "Eau de Parfum",
    availability: "Disponible en stock",
    colors: [C.negro],
    sizes: ONE_SIZE,
    rating: 4.7,
    badge: "Más vendido",
  },
  {
    id: "p86",
    slug: "nova-femme-eau-de-parfum-p86",
    name: "Nova Femme Eau de Parfum",
    description: "Fragancia femenina floral con fondo almizclado.",
    longDescription: "Fragancia femenina floral con fondo almizclado. Confeccionada en eau de parfum, esta pieza de la línea fragancias de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 399,
    image: "/product-images/p086.jpg",
    images: ["/product-images/p086.jpg"],
    category: "fragancias",
    categoryLabel: CATEGORY_LABEL.fragancias,
    type: "Fragancias",
    style: "Fragancias",
    material: "Eau de Parfum",
    availability: "Disponible en stock",
    colors: [C.rosa],
    sizes: ONE_SIZE,
    rating: 4.8,
    badge: undefined,
  },
  {
    id: "p87",
    slug: "nova-blanc-cologne-p87",
    name: "Nova Blanc Cologne",
    description: "Colonia fresca de notas cítricas y acuáticas.",
    longDescription: "Colonia fresca de notas cítricas y acuáticas. Confeccionada en cologne, esta pieza de la línea fragancias de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 329,
    image: "/product-images/p087.jpg",
    images: ["/product-images/p087.jpg"],
    category: "fragancias",
    categoryLabel: CATEGORY_LABEL.fragancias,
    type: "Fragancias",
    style: "Fragancias",
    material: "Cologne",
    availability: "Disponible en stock",
    colors: [C.blanco],
    sizes: ONE_SIZE,
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p88",
    slug: "nova-rose-eau-de-toilette-p88",
    name: "Nova Rose Eau de Toilette",
    description: "Eau de toilette floral con notas de rosa y vainilla.",
    longDescription: "Eau de toilette floral con notas de rosa y vainilla. Confeccionada en eau de toilette, esta pieza de la línea fragancias de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 349,
    image: "/product-images/p088.jpg",
    images: ["/product-images/p088.jpg"],
    category: "fragancias",
    categoryLabel: CATEGORY_LABEL.fragancias,
    type: "Fragancias",
    style: "Fragancias",
    material: "Eau de Toilette",
    availability: "Disponible en stock",
    colors: [C.rosa],
    sizes: ONE_SIZE,
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p89",
    slug: "nova-bloom-perfume-p89",
    name: "Nova Bloom Perfume",
    description: "Perfume floral fresco ideal para uso diario.",
    longDescription: "Perfume floral fresco ideal para uso diario. Confeccionada en eau de parfum, esta pieza de la línea fragancias de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 369,
    image: "/product-images/p089.jpg",
    images: ["/product-images/p089.jpg"],
    category: "fragancias",
    categoryLabel: CATEGORY_LABEL.fragancias,
    type: "Fragancias",
    style: "Fragancias",
    material: "Eau de Parfum",
    availability: "Últimas unidades",
    colors: [C.morado],
    sizes: ONE_SIZE,
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p90",
    slug: "serum-facial-hidratante-p90",
    name: "Sérum Facial Hidratante",
    description: "Sérum facial de ácido hialurónico para hidratación profunda.",
    longDescription: "Sérum facial de ácido hialurónico para hidratación profunda. Confeccionada en sérum cosmético, esta pieza de la línea skincare de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 249,
    image: "/product-images/p090.jpg",
    images: ["/product-images/p090.jpg"],
    category: "skincare",
    categoryLabel: CATEGORY_LABEL.skincare,
    type: "Skincare",
    style: "Skincare",
    material: "Sérum cosmético",
    availability: "Disponible en stock",
    colors: [C.blanco],
    sizes: ONE_SIZE,
    rating: 4.7,
    badge: "Más vendido",
  },
  {
    id: "p91",
    slug: "crema-facial-nutritiva-nova-p91",
    name: "Crema Facial Nutritiva Nova",
    description: "Crema facial nutritiva para uso diario.",
    longDescription: "Crema facial nutritiva para uso diario. Confeccionada en crema cosmética, esta pieza de la línea skincare de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 229,
    image: "/product-images/p091.jpg",
    images: ["/product-images/p091.jpg"],
    category: "skincare",
    categoryLabel: CATEGORY_LABEL.skincare,
    type: "Skincare",
    style: "Skincare",
    material: "Crema cosmética",
    availability: "Disponible en stock",
    colors: [C.blanco, C.beige],
    sizes: ONE_SIZE,
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p92",
    slug: "serum-vitamina-c-nova-p92",
    name: "Sérum Vitamina C Nova",
    description: "Sérum iluminador con vitamina C para un aspecto radiante.",
    longDescription: "Sérum iluminador con vitamina C para un aspecto radiante. Confeccionada en sérum cosmético, esta pieza de la línea skincare de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 259,
    image: "/product-images/p092.jpg",
    images: ["/product-images/p092.jpg"],
    category: "skincare",
    categoryLabel: CATEGORY_LABEL.skincare,
    type: "Skincare",
    style: "Skincare",
    material: "Sérum cosmético",
    availability: "Disponible en stock",
    colors: [C.blanco],
    sizes: ONE_SIZE,
    rating: 4.7,
    badge: undefined,
  },
  {
    id: "p93",
    slug: "contorno-de-ojos-nova-p93",
    name: "Contorno de Ojos Nova",
    description: "Contorno de ojos ligero para piel de aspecto descansado.",
    longDescription: "Contorno de ojos ligero para piel de aspecto descansado. Confeccionada en crema cosmética, esta pieza de la línea skincare de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 219,
    image: "/product-images/p093.jpg",
    images: ["/product-images/p093.jpg"],
    category: "skincare",
    categoryLabel: CATEGORY_LABEL.skincare,
    type: "Skincare",
    style: "Skincare",
    material: "Crema cosmética",
    availability: "Disponible en stock",
    colors: [C.blanco],
    sizes: ONE_SIZE,
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p94",
    slug: "kit-afeitado-nova-grooming-p94",
    name: "Kit Afeitado Nova Grooming",
    description: "Kit de afeitado con espuma y accesorios de cuidado.",
    longDescription: "Kit de afeitado con espuma y accesorios de cuidado. Confeccionada en kit de grooming, esta pieza de la línea cuidado personal de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 349,
    image: "/product-images/p094.jpg",
    images: ["/product-images/p094.jpg"],
    category: "cuidado",
    categoryLabel: CATEGORY_LABEL.cuidado,
    type: "Baño",
    style: "Cuidado personal",
    material: "Kit de grooming",
    availability: "Disponible en stock",
    colors: [C.negro, C.gris],
    sizes: ONE_SIZE,
    rating: 4.7,
    badge: undefined,
  },
  {
    id: "p95",
    slug: "crema-de-manos-nova-soft-p95",
    name: "Crema de Manos Nova Soft",
    description: "Crema de manos de absorción rápida y aroma delicado.",
    longDescription: "Crema de manos de absorción rápida y aroma delicado. Confeccionada en crema de manos, esta pieza de la línea cuidado personal de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 99,
    image: "/product-images/p095.jpg",
    images: ["/product-images/p095.jpg"],
    category: "cuidado",
    categoryLabel: CATEGORY_LABEL.cuidado,
    type: "Cuerpo",
    style: "Cuidado personal",
    material: "Crema de manos",
    availability: "Disponible en stock",
    colors: [C.rosa, C.blanco],
    sizes: ONE_SIZE,
    rating: 4.5,
    badge: undefined,
  },
  {
    id: "p96",
    slug: "aceite-corporal-relax-nova-p96",
    name: "Aceite Corporal Relax Nova",
    description: "Aceite corporal relajante para masaje diario.",
    longDescription: "Aceite corporal relajante para masaje diario. Confeccionada en aceite corporal, esta pieza de la línea cuidado personal de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 199,
    image: "/product-images/p096.jpg",
    images: ["/product-images/p096.jpg"],
    category: "cuidado",
    categoryLabel: CATEGORY_LABEL.cuidado,
    type: "Cuerpo",
    style: "Cuidado personal",
    material: "Aceite corporal",
    availability: "Disponible en stock",
    colors: [C.blanco, C.beige],
    sizes: ONE_SIZE,
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p97",
    slug: "paleta-sombras-nova-glam-p97",
    name: "Paleta Sombras Nova Glam",
    description: "Paleta de sombras de tonos versátiles, mate y satinados.",
    longDescription: "Paleta de sombras de tonos versátiles, mate y satinados. Confeccionada en paleta de sombras, esta pieza de la línea maquillaje de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 319,
    image: "/product-images/p097.jpg",
    images: ["/product-images/p097.jpg"],
    category: "maquillaje",
    categoryLabel: CATEGORY_LABEL.maquillaje,
    type: "Belleza",
    style: "Maquillaje",
    material: "Paleta de sombras",
    availability: "Disponible en stock",
    colors: [C.morado, C.dorado],
    sizes: ONE_SIZE,
    rating: 4.7,
    badge: "Nuevo",
  },
  {
    id: "p98",
    slug: "set-belleza-maquillaje-nova-p98",
    name: "Set Belleza Maquillaje Nova",
    description: "Set de productos de maquillaje esenciales para el día a día.",
    longDescription: "Set de productos de maquillaje esenciales para el día a día. Confeccionada en kit cosmético, esta pieza de la línea maquillaje de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 399,
    image: "/product-images/p098.jpg",
    images: ["/product-images/p098.jpg"],
    category: "maquillaje",
    categoryLabel: CATEGORY_LABEL.maquillaje,
    type: "Belleza",
    style: "Maquillaje",
    material: "Kit cosmético",
    availability: "Disponible en stock",
    colors: [C.rosa, C.negro],
    sizes: ONE_SIZE,
    rating: 4.6,
    badge: undefined,
  },
  {
    id: "p99",
    slug: "labial-mate-nova-p99",
    name: "Labial Mate Nova",
    description: "Labial de acabado mate de larga duración.",
    longDescription: "Labial de acabado mate de larga duración. Confeccionada en labial cosmético, esta pieza de la línea maquillaje de NOVASTYLE combina calidad y diseño contemporáneo. Ideal para el uso diario.",
    price: 139,
    image: "/product-images/p099.jpg",
    images: ["/product-images/p099.jpg"],
    category: "maquillaje",
    categoryLabel: CATEGORY_LABEL.maquillaje,
    type: "Labios",
    style: "Maquillaje",
    material: "Labial cosmético",
    availability: "Disponible en stock",
    colors: [C.rosa, C.vino],
    sizes: ONE_SIZE,
    rating: 4.7,
    badge: "Más vendido",
  },
];

export const CATEGORIES: { key: string; label: string }[] = [
  { key: "todos", label: "Todos" },
  { key: "hombre", label: "Hombre" },
  { key: "mujer", label: "Mujer" },
  { key: "ninos", label: "Niños" },
  { key: "ninas", label: "Niñas" },
  { key: "calzado", label: "Calzado" },
  { key: "bolsos", label: "Bolsos" },
  { key: "joyeria", label: "Joyería" },
  { key: "accesorios", label: "Accesorios" },
  { key: "fragancias", label: "Fragancias" },
  { key: "skincare", label: "Skincare" },
  { key: "cuidado", label: "Cuidado personal" },
  { key: "maquillaje", label: "Maquillaje" },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return PRODUCTS.filter((p) => p.category === product.category && p.id !== product.id).slice(0, limit);
}


// Compatibilidad con la pagina de detalle de producto.
export const VIEW_LABELS = ["Fotografía del producto"];

export const getProduct = (id: string) =>
  PRODUCTS.find((p) => p.id === id || p.slug === id);

export const relatedProducts = (p: Product, n = 6) =>
  PRODUCTS.filter((x) => x.id !== p.id && (x.category === p.category || x.style === p.style)).slice(0, n);

export const SIZE_GUIDE = {
  adulto: {
    title: "Ropa adulto (cm)",
    head: ["Talla", "Pecho", "Cintura", "Cadera"],
    rows: [
      ["XS", "82-86", "64-68", "88-92"],
      ["S", "87-91", "69-73", "93-97"],
      ["M", "92-97", "74-79", "98-103"],
      ["L", "98-103", "80-85", "104-109"],
      ["XL", "104-110", "86-92", "110-116"],
      ["XXL", "111-117", "93-99", "117-123"],
    ],
  },
  ninos: {
    title: "Ropa infantil",
    head: ["Talla", "Edad", "Estatura (cm)"],
    rows: [
      ["2A", "2 años", "88-94"], ["4A", "4 años", "100-106"],
      ["6A", "6 años", "112-118"], ["8A", "8 años", "124-130"],
      ["10A", "10 años", "136-142"], ["12A", "12 años", "148-154"],
    ],
  },
  calzado: {
    title: "Calzado (cm de plantilla)",
    head: ["Talla", "Longitud"],
    rows: [
      ["35", "22.5"], ["36", "23.0"], ["37", "23.5"], ["38", "24.5"],
      ["39", "25.0"], ["40", "25.5"], ["41", "26.5"], ["42", "27.0"], ["43", "27.5"],
    ],
  },
};
