/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UbicacionRouteImport } from './routes/ubicacion'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as RedesSocialesRouteImport } from './routes/redes-sociales'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as InviertaRouteImport } from './routes/invierta'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const UbicacionRoute = UbicacionRouteImport.update({
  id: '/ubicacion',
  path: '/ubicacion',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const RedesSocialesRoute = RedesSocialesRouteImport.update({
  id: '/redes-sociales',
  path: '/redes-sociales',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const InviertaRoute = InviertaRouteImport.update({
  id: '/invierta',
  path: '/invierta',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/invierta': typeof InviertaRoute
  '/noticias': typeof NoticiasRoute
  '/productos': typeof ProductosRoute
  '/redes-sociales': typeof RedesSocialesRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/ubicacion': typeof UbicacionRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/producto/$id': typeof ProductoIdRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/invierta': typeof InviertaRoute
  '/noticias': typeof NoticiasRoute
  '/productos': typeof ProductosRoute
  '/redes-sociales': typeof RedesSocialesRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/ubicacion': typeof UbicacionRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/producto/$id': typeof ProductoIdRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/invierta': typeof InviertaRoute
  '/noticias': typeof NoticiasRoute
  '/productos': typeof ProductosRoute
  '/redes-sociales': typeof RedesSocialesRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/ubicacion': typeof UbicacionRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/producto/$id': typeof ProductoIdRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/contacto'
    | '/faq'
    | '/invierta'
    | '/noticias'
    | '/productos'
    | '/redes-sociales'
    | '/sobre-nosotros'
    | '/ubicacion'
    | '/blog/$slug'
    | '/producto/$id'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/contacto'
    | '/faq'
    | '/invierta'
    | '/noticias'
    | '/productos'
    | '/redes-sociales'
    | '/sobre-nosotros'
    | '/ubicacion'
    | '/blog/$slug'
    | '/producto/$id'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/contacto'
    | '/faq'
    | '/invierta'
    | '/noticias'
    | '/productos'
    | '/redes-sociales'
    | '/sobre-nosotros'
    | '/ubicacion'
    | '/blog/$slug'
    | '/producto/$id'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactoRoute: typeof ContactoRoute
  FaqRoute: typeof FaqRoute
  InviertaRoute: typeof InviertaRoute
  NoticiasRoute: typeof NoticiasRoute
  ProductosRoute: typeof ProductosRoute
  RedesSocialesRoute: typeof RedesSocialesRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  UbicacionRoute: typeof UbicacionRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProductoIdRoute: typeof ProductoIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ubicacion': {
      id: '/ubicacion'
      path: '/ubicacion'
      fullPath: '/ubicacion'
      preLoaderRoute: typeof UbicacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redes-sociales': {
      id: '/redes-sociales'
      path: '/redes-sociales'
      fullPath: '/redes-sociales'
      preLoaderRoute: typeof RedesSocialesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invierta': {
      id: '/invierta'
      path: '/invierta'
      fullPath: '/invierta'
      preLoaderRoute: typeof InviertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ContactoRoute: ContactoRoute,
  FaqRoute: FaqRoute,
  InviertaRoute: InviertaRoute,
  NoticiasRoute: NoticiasRoute,
  ProductosRoute: ProductosRoute,
  RedesSocialesRoute: RedesSocialesRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  UbicacionRoute: UbicacionRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProductoIdRoute: ProductoIdRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
